; added a launchpad perspective for each drone
; added the is-clear-perspective for the relevant perspectives in the initial state



(define (problem asi-dur-problem-fullswap)
  (:domain asi-dur-domain-fullswap)
 
  (:objects 
	
    s7-tower-launchpad s7-antenna-1 s7-antenna-2 s7-antenna-3 s7-antenna-4 s7-antenna-5 s7-antenna-6 - component
    s8-tower-launchpad s8-antenna-1 s8-antenna-2 s8-antenna-3 s8-antenna-4 s8-antenna-5 s8-antenna-6 - component
    s9-tower-launchpad s9-antenna-1 s9-antenna-2 s9-antenna-3 s9-antenna-4 s9-antenna-5 s9-antenna-6 - component
    s10-tower-launchpad s10-antenna-1 s10-antenna-2 s10-antenna-3 s10-antenna-4 s10-antenna-5 s10-antenna-6 - component
    s11-tower-launchpad s11-antenna-1 s11-antenna-2 s11-antenna-3 s11-antenna-4 s11-antenna-5 s11-antenna-6 - component
    s12-tower-launchpad s12-antenna-1 s12-antenna-2 s12-antenna-3 s12-antenna-4 s12-antenna-5 s12-antenna-6 - component
    
    front above below left right front-below launch-pad dock radiation-pattern dynamic-inspection360 - perspective 
    drone3 - drone
    drone1 drone2 - drone

  
  )

  (:init

    ;individual inspection configurations
    (= (inspection-duration image) 1)
    (= (inspection-duration thermal-image) 2)
    (= (inspection-duration signal-measurement) 2)
    
    (= (capability-consumption camera) 2)
    (= (capability-consumption thermal-camera) 2)
    (= (capability-consumption signal-measurer) 2)

    (inspects camera image)
    (inspects thermal-camera thermal-image)
    (inspects signal-measurer signal-measurement)

    ;!!!! ADD TILS !!!!!!


;    in strand, single til of one type is at the same waypoint
;    in pandora, mutiple tils of one type are at multiple waypoints
;    in drones, mutiple tils of one type are at multiple waypoints
;        which til?
;            charge only in daytime - no as in strategic level


    ;distance between components
    (= (distance s7-tower-launchpad s8-tower-launchpad) 40.6126148)
    (= (distance s7-tower-launchpad s9-tower-launchpad) 40.6126148)
    (= (distance s7-tower-launchpad s10-tower-launchpad) 217.145992)
    (= (distance s7-tower-launchpad s11-tower-launchpad) 252.527444)
    (= (distance s7-tower-launchpad s12-tower-launchpad) 251.580256)
    (= (distance s8-tower-launchpad s7-tower-launchpad) 40.6126148)
    (= (distance s8-tower-launchpad s9-tower-launchpad) 29.1339746)
    (= (distance s8-tower-launchpad s10-tower-launchpad) 178.959128)
    (= (distance s8-tower-launchpad s11-tower-launchpad) 213.15426)
    (= (distance s8-tower-launchpad s12-tower-launchpad) 215.196571)
    (= (distance s9-tower-launchpad s7-tower-launchpad) 40.6126148)
    (= (distance s9-tower-launchpad s8-tower-launchpad) 29.1339746)
    (= (distance s9-tower-launchpad s10-tower-launchpad) 180.817377)
    (= (distance s9-tower-launchpad s11-tower-launchpad) 217.907972)
    (= (distance s9-tower-launchpad s12-tower-launchpad) 213.272067)
    (= (distance s10-tower-launchpad s7-tower-launchpad) 217.145992)
    (= (distance s10-tower-launchpad s8-tower-launchpad) 178.959128)
    (= (distance s10-tower-launchpad s9-tower-launchpad) 180.817377)
    (= (distance s10-tower-launchpad s11-tower-launchpad) 40.8072879)
    (= (distance s10-tower-launchpad s12-tower-launchpad) 42.846823)
    (= (distance s11-tower-launchpad s7-tower-launchpad) 252.527444)
    (= (distance s11-tower-launchpad s8-tower-launchpad) 213.15426)
    (= (distance s11-tower-launchpad s9-tower-launchpad) 217.907972)
    (= (distance s11-tower-launchpad s10-tower-launchpad) 40.8072879)
    (= (distance s11-tower-launchpad s12-tower-launchpad) 49.3319186)
    (= (distance s12-tower-launchpad s7-tower-launchpad) 251.580256)
    (= (distance s12-tower-launchpad s8-tower-launchpad) 215.196571)
    (= (distance s12-tower-launchpad s9-tower-launchpad) 213.272067)
    (= (distance s12-tower-launchpad s10-tower-launchpad) 42.846823)
    (= (distance s12-tower-launchpad s11-tower-launchpad) 49.3319186)



    ;s7-site

    (is-perspective launch-pad s7-tower-launchpad)
    (is-charging-dock s7-tower-launchpad launch-pad)
    (= (distance s7-tower-launchpad s7-antenna-1) 7)
    (= (distance s7-tower-launchpad s7-antenna-2) 7)
    (= (distance s7-tower-launchpad s7-antenna-3) 8)
    (= (distance s7-tower-launchpad s7-antenna-4) 8)
    (= (distance s7-tower-launchpad s7-antenna-5) 7)
    (= (distance s7-tower-launchpad s7-antenna-6) 7)

    (is-perspective dynamic-inspection360 s7-antenna-1)
    (is-perspective radiation-pattern s7-antenna-1)
    (is-perspective dock s7-antenna-1)
    (is-perspective front s7-antenna-1)
    (is-perspective above s7-antenna-1)
    (is-perspective below s7-antenna-1)
    (is-perspective left s7-antenna-1)
    (is-perspective right s7-antenna-1)
    (is-perspective front-below s7-antenna-1)
    (is-clear-perspective dynamic-inspection360 s7-antenna-1)
    (is-clear-perspective radiation-pattern s7-antenna-1)
    (is-clear-perspective front s7-antenna-1)
    (is-clear-perspective above s7-antenna-1)
    (is-clear-perspective below s7-antenna-1)
    (is-clear-perspective left s7-antenna-1)
    (is-clear-perspective right s7-antenna-1)
    (is-clear-perspective front-below s7-antenna-1)
    (= (distance s7-antenna-1 s7-tower-launchpad) 29)
    (= (distance s7-antenna-1 s7-antenna-2) 1)
    (= (distance s7-antenna-1 s7-antenna-3) 2)
    (= (distance s7-antenna-1 s7-antenna-4) 2)
    (= (distance s7-antenna-1 s7-antenna-5) 2)
    (= (distance s7-antenna-1 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-2)
    (is-perspective radiation-pattern s7-antenna-2)
    (is-perspective dock s7-antenna-2)
    (is-perspective front s7-antenna-2)
    (is-perspective above s7-antenna-2)
    (is-perspective below s7-antenna-2)
    (is-perspective left s7-antenna-2)
    (is-perspective right s7-antenna-2)
    (is-perspective front-below s7-antenna-2)
    (is-clear-perspective dynamic-inspection360 s7-antenna-2)
    (is-clear-perspective radiation-pattern s7-antenna-2)
    (is-clear-perspective front s7-antenna-2)
    (is-clear-perspective above s7-antenna-2)
    (is-clear-perspective below s7-antenna-2)
    (is-clear-perspective left s7-antenna-2)
    (is-clear-perspective right s7-antenna-2)
    (is-clear-perspective front-below s7-antenna-2)
    (= (distance s7-antenna-2 s7-tower-launchpad) 29)
    (= (distance s7-antenna-2 s7-antenna-1) 1)
    (= (distance s7-antenna-2 s7-antenna-3) 2)
    (= (distance s7-antenna-2 s7-antenna-4) 2)
    (= (distance s7-antenna-2 s7-antenna-5) 2)
    (= (distance s7-antenna-2 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-3)
    (is-perspective radiation-pattern s7-antenna-3)
    (is-perspective dock s7-antenna-3)
    (is-perspective front s7-antenna-3)
    (is-perspective above s7-antenna-3)
    (is-perspective below s7-antenna-3)
    (is-perspective left s7-antenna-3)
    (is-perspective right s7-antenna-3)
    (is-perspective front-below s7-antenna-3)
    (is-clear-perspective dynamic-inspection360 s7-antenna-3)
    (is-clear-perspective radiation-pattern s7-antenna-3)
    (is-clear-perspective front s7-antenna-3)
    (is-clear-perspective above s7-antenna-3)
    (is-clear-perspective below s7-antenna-3)
    (is-clear-perspective left s7-antenna-3)
    (is-clear-perspective right s7-antenna-3)
    (is-clear-perspective front-below s7-antenna-3)
    (= (distance s7-antenna-3 s7-tower-launchpad) 30)
    (= (distance s7-antenna-3 s7-antenna-1) 2)
    (= (distance s7-antenna-3 s7-antenna-2) 2)
    (= (distance s7-antenna-3 s7-antenna-4) 1)
    (= (distance s7-antenna-3 s7-antenna-5) 2)
    (= (distance s7-antenna-3 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-4)
    (is-perspective radiation-pattern s7-antenna-4)
    (is-perspective dock s7-antenna-4)
    (is-perspective front s7-antenna-4)
    (is-perspective above s7-antenna-4)
    (is-perspective below s7-antenna-4)
    (is-perspective left s7-antenna-4)
    (is-perspective right s7-antenna-4)
    (is-perspective front-below s7-antenna-4)
    (is-clear-perspective dynamic-inspection360 s7-antenna-4)
    (is-clear-perspective radiation-pattern s7-antenna-4)
    (is-clear-perspective front s7-antenna-4)
    (is-clear-perspective above s7-antenna-4)
    (is-clear-perspective below s7-antenna-4)
    (is-clear-perspective left s7-antenna-4)
    (is-clear-perspective right s7-antenna-4)
    (is-clear-perspective front-below s7-antenna-4)
    (= (distance s7-antenna-4 s7-tower-launchpad) 30)
    (= (distance s7-antenna-4 s7-antenna-1) 2)
    (= (distance s7-antenna-4 s7-antenna-2) 2)
    (= (distance s7-antenna-4 s7-antenna-3) 1)
    (= (distance s7-antenna-4 s7-antenna-5) 2)
    (= (distance s7-antenna-4 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-5)
    (is-perspective radiation-pattern s7-antenna-5)
    (is-perspective dock s7-antenna-5)
    (is-perspective front s7-antenna-5)
    (is-perspective above s7-antenna-5)
    (is-perspective below s7-antenna-5)
    (is-perspective left s7-antenna-5)
    (is-perspective right s7-antenna-5)
    (is-perspective front-below s7-antenna-5)
    (is-clear-perspective dynamic-inspection360 s7-antenna-5)
    (is-clear-perspective radiation-pattern s7-antenna-5)
    (is-clear-perspective front s7-antenna-5)
    (is-clear-perspective above s7-antenna-5)
    (is-clear-perspective below s7-antenna-5)
    (is-clear-perspective left s7-antenna-5)
    (is-clear-perspective right s7-antenna-5)
    (is-clear-perspective front-below s7-antenna-5)
    (= (distance s7-antenna-5 s7-tower-launchpad) 29)
    (= (distance s7-antenna-5 s7-antenna-1) 2)
    (= (distance s7-antenna-5 s7-antenna-2) 2)
    (= (distance s7-antenna-5 s7-antenna-3) 2)
    (= (distance s7-antenna-5 s7-antenna-4) 2)
    (= (distance s7-antenna-5 s7-antenna-6) 1)

    (is-perspective dynamic-inspection360 s7-antenna-6)
    (is-perspective radiation-pattern s7-antenna-6)
    (is-perspective dock s7-antenna-6)
    (is-perspective front s7-antenna-6)
    (is-perspective above s7-antenna-6)
    (is-perspective below s7-antenna-6)
    (is-perspective left s7-antenna-6)
    (is-perspective right s7-antenna-6)
    (is-perspective front-below s7-antenna-6)
    (is-clear-perspective dynamic-inspection360 s7-antenna-6)
    (is-clear-perspective radiation-pattern s7-antenna-6)
    (is-clear-perspective front s7-antenna-6)
    (is-clear-perspective above s7-antenna-6)
    (is-clear-perspective below s7-antenna-6)
    (is-clear-perspective left s7-antenna-6)
    (is-clear-perspective right s7-antenna-6)
    (is-clear-perspective front-below s7-antenna-6)
    (= (distance s7-antenna-6 s7-tower-launchpad) 29)
    (= (distance s7-antenna-6 s7-antenna-1) 2)
    (= (distance s7-antenna-6 s7-antenna-2) 2)
    (= (distance s7-antenna-6 s7-antenna-3) 2)
    (= (distance s7-antenna-6 s7-antenna-4) 2)
    (= (distance s7-antenna-6 s7-antenna-5) 1)

    (= (max-dock s7-tower-launchpad) 0) 
    (= (max-dock s7-antenna-1) 3)
    (= (max-dock s7-antenna-2) 3) 
    (= (max-dock s7-antenna-3) 3) 
    (= (max-dock s7-antenna-4) 3) 
    (= (max-dock s7-antenna-5) 3) 
    (= (max-dock s7-antenna-6) 3)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;s8-site

    (is-perspective launch-pad s8-tower-launchpad)
    ;(is-charging-dock s8-tower-launchpad launch-pad)
    (= (distance s8-tower-launchpad s8-antenna-1) 7)
    (= (distance s8-tower-launchpad s8-antenna-2) 7)
    (= (distance s8-tower-launchpad s8-antenna-3) 8)
    (= (distance s8-tower-launchpad s8-antenna-4) 8)
    (= (distance s8-tower-launchpad s8-antenna-5) 7)
    (= (distance s8-tower-launchpad s8-antenna-6) 7)

    (is-perspective dynamic-inspection360 s8-antenna-1)
    (is-perspective radiation-pattern s8-antenna-1)
    (is-perspective dock s8-antenna-1)
    (is-perspective front s8-antenna-1)
    (is-perspective above s8-antenna-1)
    (is-perspective below s8-antenna-1)
    (is-perspective left s8-antenna-1)
    (is-perspective right s8-antenna-1)
    (is-perspective front-below s8-antenna-1)
    (is-clear-perspective dynamic-inspection360 s8-antenna-1)
    (is-clear-perspective radiation-pattern s8-antenna-1)
    (is-clear-perspective front s8-antenna-1)
    (is-clear-perspective above s8-antenna-1)
    (is-clear-perspective below s8-antenna-1)
    (is-clear-perspective left s8-antenna-1)
    (is-clear-perspective right s8-antenna-1)
    (is-clear-perspective front-below s8-antenna-1)
    (= (distance s8-antenna-1 s8-tower-launchpad) 29)
    (= (distance s8-antenna-1 s8-antenna-2) 1)
    (= (distance s8-antenna-1 s8-antenna-3) 2)
    (= (distance s8-antenna-1 s8-antenna-4) 2)
    (= (distance s8-antenna-1 s8-antenna-5) 2)
    (= (distance s8-antenna-1 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-2)
    (is-perspective radiation-pattern s8-antenna-2)
    (is-perspective dock s8-antenna-2)
    (is-perspective front s8-antenna-2)
    (is-perspective above s8-antenna-2)
    (is-perspective below s8-antenna-2)
    (is-perspective left s8-antenna-2)
    (is-perspective right s8-antenna-2)
    (is-perspective front-below s8-antenna-2)
    (is-clear-perspective dynamic-inspection360 s8-antenna-2)
    (is-clear-perspective radiation-pattern s8-antenna-2)
    (is-clear-perspective front s8-antenna-2)
    (is-clear-perspective above s8-antenna-2)
    (is-clear-perspective below s8-antenna-2)
    (is-clear-perspective left s8-antenna-2)
    (is-clear-perspective right s8-antenna-2)
    (is-clear-perspective front-below s8-antenna-2)
    (= (distance s8-antenna-2 s8-tower-launchpad) 29)
    (= (distance s8-antenna-2 s8-antenna-1) 1)
    (= (distance s8-antenna-2 s8-antenna-3) 2)
    (= (distance s8-antenna-2 s8-antenna-4) 2)
    (= (distance s8-antenna-2 s8-antenna-5) 2)
    (= (distance s8-antenna-2 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-3)
    (is-perspective radiation-pattern s8-antenna-3)
    (is-perspective dock s8-antenna-3)
    (is-perspective front s8-antenna-3)
    (is-perspective above s8-antenna-3)
    (is-perspective below s8-antenna-3)
    (is-perspective left s8-antenna-3)
    (is-perspective right s8-antenna-3)
    (is-perspective front-below s8-antenna-3)
    (is-clear-perspective dynamic-inspection360 s8-antenna-3)
    (is-clear-perspective radiation-pattern s8-antenna-3)
    (is-clear-perspective front s8-antenna-3)
    (is-clear-perspective above s8-antenna-3)
    (is-clear-perspective below s8-antenna-3)
    (is-clear-perspective left s8-antenna-3)
    (is-clear-perspective right s8-antenna-3)
    (is-clear-perspective front-below s8-antenna-3)
    (= (distance s8-antenna-3 s8-tower-launchpad) 30)
    (= (distance s8-antenna-3 s8-antenna-1) 2)
    (= (distance s8-antenna-3 s8-antenna-2) 2)
    (= (distance s8-antenna-3 s8-antenna-4) 1)
    (= (distance s8-antenna-3 s8-antenna-5) 2)
    (= (distance s8-antenna-3 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-4)
    (is-perspective radiation-pattern s8-antenna-4)
    (is-perspective dock s8-antenna-4)
    (is-perspective front s8-antenna-4)
    (is-perspective above s8-antenna-4)
    (is-perspective below s8-antenna-4)
    (is-perspective left s8-antenna-4)
    (is-perspective right s8-antenna-4)
    (is-perspective front-below s8-antenna-4)
    (is-clear-perspective dynamic-inspection360 s8-antenna-4)
    (is-clear-perspective radiation-pattern s8-antenna-4)
    (is-clear-perspective front s8-antenna-4)
    (is-clear-perspective above s8-antenna-4)
    (is-clear-perspective below s8-antenna-4)
    (is-clear-perspective left s8-antenna-4)
    (is-clear-perspective right s8-antenna-4)
    (is-clear-perspective front-below s8-antenna-4)
    (= (distance s8-antenna-4 s8-tower-launchpad) 30)
    (= (distance s8-antenna-4 s8-antenna-1) 2)
    (= (distance s8-antenna-4 s8-antenna-2) 2)
    (= (distance s8-antenna-4 s8-antenna-3) 1)
    (= (distance s8-antenna-4 s8-antenna-5) 2)
    (= (distance s8-antenna-4 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-5)
    (is-perspective radiation-pattern s8-antenna-5)
    (is-perspective dock s8-antenna-5)
    (is-perspective front s8-antenna-5)
    (is-perspective above s8-antenna-5)
    (is-perspective below s8-antenna-5)
    (is-perspective left s8-antenna-5)
    (is-perspective right s8-antenna-5)
    (is-perspective front-below s8-antenna-5)
    (is-clear-perspective dynamic-inspection360 s8-antenna-5)
    (is-clear-perspective radiation-pattern s8-antenna-5)
    (is-clear-perspective front s8-antenna-5)
    (is-clear-perspective above s8-antenna-5)
    (is-clear-perspective below s8-antenna-5)
    (is-clear-perspective left s8-antenna-5)
    (is-clear-perspective right s8-antenna-5)
    (is-clear-perspective front-below s8-antenna-5)
    (= (distance s8-antenna-5 s8-tower-launchpad) 29)
    (= (distance s8-antenna-5 s8-antenna-1) 2)
    (= (distance s8-antenna-5 s8-antenna-2) 2)
    (= (distance s8-antenna-5 s8-antenna-3) 2)
    (= (distance s8-antenna-5 s8-antenna-4) 2)
    (= (distance s8-antenna-5 s8-antenna-6) 1)

    (is-perspective dynamic-inspection360 s8-antenna-6)
    (is-perspective radiation-pattern s8-antenna-6)
    (is-perspective dock s8-antenna-6)
    (is-perspective front s8-antenna-6)
    (is-perspective above s8-antenna-6)
    (is-perspective below s8-antenna-6)
    (is-perspective left s8-antenna-6)
    (is-perspective right s8-antenna-6)
    (is-perspective front-below s8-antenna-6)
    (is-clear-perspective dynamic-inspection360 s8-antenna-6)
    (is-clear-perspective radiation-pattern s8-antenna-6)
    (is-clear-perspective front s8-antenna-6)
    (is-clear-perspective above s8-antenna-6)
    (is-clear-perspective below s8-antenna-6)
    (is-clear-perspective left s8-antenna-6)
    (is-clear-perspective right s8-antenna-6)
    (is-clear-perspective front-below s8-antenna-6)
    (= (distance s8-antenna-6 s8-tower-launchpad) 29)
    (= (distance s8-antenna-6 s8-antenna-1) 2)
    (= (distance s8-antenna-6 s8-antenna-2) 2)
    (= (distance s8-antenna-6 s8-antenna-3) 2)
    (= (distance s8-antenna-6 s8-antenna-4) 2)
    (= (distance s8-antenna-6 s8-antenna-5) 1)

    (= (max-dock s8-tower-launchpad) 3) 
    (= (max-dock s8-antenna-1) 3)
    (= (max-dock s8-antenna-2) 3) 
    (= (max-dock s8-antenna-3) 3) 
    (= (max-dock s8-antenna-4) 3) 
    (= (max-dock s8-antenna-5) 3) 
    (= (max-dock s8-antenna-6) 3)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;s9-site

    (is-perspective launch-pad s9-tower-launchpad)
    ;(is-charging-dock s9-tower-launchpad launch-pad)
    (= (distance s9-tower-launchpad s9-antenna-1) 7)
    (= (distance s9-tower-launchpad s9-antenna-2) 7)
    (= (distance s9-tower-launchpad s9-antenna-3) 8)
    (= (distance s9-tower-launchpad s9-antenna-4) 8)
    (= (distance s9-tower-launchpad s9-antenna-5) 7)
    (= (distance s9-tower-launchpad s9-antenna-6) 7)

    (is-perspective dynamic-inspection360 s9-antenna-1)
    (is-perspective radiation-pattern s9-antenna-1)
    (is-perspective dock s9-antenna-1)
    (is-perspective front s9-antenna-1)
    (is-perspective above s9-antenna-1)
    (is-perspective below s9-antenna-1)
    (is-perspective left s9-antenna-1)
    (is-perspective right s9-antenna-1)
    (is-perspective front-below s9-antenna-1)
    (is-clear-perspective dynamic-inspection360 s9-antenna-1)
    (is-clear-perspective radiation-pattern s9-antenna-1)
    (is-clear-perspective front s9-antenna-1)
    (is-clear-perspective above s9-antenna-1)
    (is-clear-perspective below s9-antenna-1)
    (is-clear-perspective left s9-antenna-1)
    (is-clear-perspective right s9-antenna-1)
    (is-clear-perspective front-below s9-antenna-1)
    (= (distance s9-antenna-1 s9-tower-launchpad) 29)
    (= (distance s9-antenna-1 s9-antenna-2) 1)
    (= (distance s9-antenna-1 s9-antenna-3) 2)
    (= (distance s9-antenna-1 s9-antenna-4) 2)
    (= (distance s9-antenna-1 s9-antenna-5) 2)
    (= (distance s9-antenna-1 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-2)
    (is-perspective radiation-pattern s9-antenna-2)
    (is-perspective dock s9-antenna-2)
    (is-perspective front s9-antenna-2)
    (is-perspective above s9-antenna-2)
    (is-perspective below s9-antenna-2)
    (is-perspective left s9-antenna-2)
    (is-perspective right s9-antenna-2)
    (is-perspective front-below s9-antenna-2)
    (is-clear-perspective dynamic-inspection360 s9-antenna-2)
    (is-clear-perspective radiation-pattern s9-antenna-2)
    (is-clear-perspective front s9-antenna-2)
    (is-clear-perspective above s9-antenna-2)
    (is-clear-perspective below s9-antenna-2)
    (is-clear-perspective left s9-antenna-2)
    (is-clear-perspective right s9-antenna-2)
    (is-clear-perspective front-below s9-antenna-2)
    (= (distance s9-antenna-2 s9-tower-launchpad) 29)
    (= (distance s9-antenna-2 s9-antenna-1) 1)
    (= (distance s9-antenna-2 s9-antenna-3) 2)
    (= (distance s9-antenna-2 s9-antenna-4) 2)
    (= (distance s9-antenna-2 s9-antenna-5) 2)
    (= (distance s9-antenna-2 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-3)
    (is-perspective radiation-pattern s9-antenna-3)
    (is-perspective dock s9-antenna-3)
    (is-perspective front s9-antenna-3)
    (is-perspective above s9-antenna-3)
    (is-perspective below s9-antenna-3)
    (is-perspective left s9-antenna-3)
    (is-perspective right s9-antenna-3)
    (is-perspective front-below s9-antenna-3)
    (is-clear-perspective dynamic-inspection360 s9-antenna-3)
    (is-clear-perspective radiation-pattern s9-antenna-3)
    (is-clear-perspective front s9-antenna-3)
    (is-clear-perspective above s9-antenna-3)
    (is-clear-perspective below s9-antenna-3)
    (is-clear-perspective left s9-antenna-3)
    (is-clear-perspective right s9-antenna-3)
    (is-clear-perspective front-below s9-antenna-3)
    (= (distance s9-antenna-3 s9-tower-launchpad) 30)
    (= (distance s9-antenna-3 s9-antenna-1) 2)
    (= (distance s9-antenna-3 s9-antenna-2) 2)
    (= (distance s9-antenna-3 s9-antenna-4) 1)
    (= (distance s9-antenna-3 s9-antenna-5) 2)
    (= (distance s9-antenna-3 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-4)
    (is-perspective radiation-pattern s9-antenna-4)
    (is-perspective dock s9-antenna-4)
    (is-perspective front s9-antenna-4)
    (is-perspective above s9-antenna-4)
    (is-perspective below s9-antenna-4)
    (is-perspective left s9-antenna-4)
    (is-perspective right s9-antenna-4)
    (is-perspective front-below s9-antenna-4)
    (is-clear-perspective dynamic-inspection360 s9-antenna-4)
    (is-clear-perspective radiation-pattern s9-antenna-4)
    (is-clear-perspective front s9-antenna-4)
    (is-clear-perspective above s9-antenna-4)
    (is-clear-perspective below s9-antenna-4)
    (is-clear-perspective left s9-antenna-4)
    (is-clear-perspective right s9-antenna-4)
    (is-clear-perspective front-below s9-antenna-4)
    (= (distance s9-antenna-4 s9-tower-launchpad) 30)
    (= (distance s9-antenna-4 s9-antenna-1) 2)
    (= (distance s9-antenna-4 s9-antenna-2) 2)
    (= (distance s9-antenna-4 s9-antenna-3) 1)
    (= (distance s9-antenna-4 s9-antenna-5) 2)
    (= (distance s9-antenna-4 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-5)
    (is-perspective radiation-pattern s9-antenna-5)
    (is-perspective dock s9-antenna-5)
    (is-perspective front s9-antenna-5)
    (is-perspective above s9-antenna-5)
    (is-perspective below s9-antenna-5)
    (is-perspective left s9-antenna-5)
    (is-perspective right s9-antenna-5)
    (is-perspective front-below s9-antenna-5)
    (is-clear-perspective dynamic-inspection360 s9-antenna-5)
    (is-clear-perspective radiation-pattern s9-antenna-5)
    (is-clear-perspective front s9-antenna-5)
    (is-clear-perspective above s9-antenna-5)
    (is-clear-perspective below s9-antenna-5)
    (is-clear-perspective left s9-antenna-5)
    (is-clear-perspective right s9-antenna-5)
    (is-clear-perspective front-below s9-antenna-5)
    (= (distance s9-antenna-5 s9-tower-launchpad) 29)
    (= (distance s9-antenna-5 s9-antenna-1) 2)
    (= (distance s9-antenna-5 s9-antenna-2) 2)
    (= (distance s9-antenna-5 s9-antenna-3) 2)
    (= (distance s9-antenna-5 s9-antenna-4) 2)
    (= (distance s9-antenna-5 s9-antenna-6) 1)

    (is-perspective dynamic-inspection360 s9-antenna-6)
    (is-perspective radiation-pattern s9-antenna-6)
    (is-perspective dock s9-antenna-6)
    (is-perspective front s9-antenna-6)
    (is-perspective above s9-antenna-6)
    (is-perspective below s9-antenna-6)
    (is-perspective left s9-antenna-6)
    (is-perspective right s9-antenna-6)
    (is-perspective front-below s9-antenna-6)
    (is-clear-perspective dynamic-inspection360 s9-antenna-6)
    (is-clear-perspective radiation-pattern s9-antenna-6)
    (is-clear-perspective front s9-antenna-6)
    (is-clear-perspective above s9-antenna-6)
    (is-clear-perspective below s9-antenna-6)
    (is-clear-perspective left s9-antenna-6)
    (is-clear-perspective right s9-antenna-6)
    (is-clear-perspective front-below s9-antenna-6)
    (= (distance s9-antenna-6 s9-tower-launchpad) 29)
    (= (distance s9-antenna-6 s9-antenna-1) 2)
    (= (distance s9-antenna-6 s9-antenna-2) 2)
    (= (distance s9-antenna-6 s9-antenna-3) 2)
    (= (distance s9-antenna-6 s9-antenna-4) 2)
    (= (distance s9-antenna-6 s9-antenna-5) 1)

    (= (max-dock s9-tower-launchpad) 3) 
    (= (max-dock s9-antenna-1) 3)
    (= (max-dock s9-antenna-2) 3) 
    (= (max-dock s9-antenna-3) 3) 
    (= (max-dock s9-antenna-4) 3) 
    (= (max-dock s9-antenna-5) 3) 
    (= (max-dock s9-antenna-6) 3)


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ; ;s10-site

    ; (is-perspective launch-pad s10-tower-launchpad)
    ; (is-charging-dock s10-tower-launchpad launch-pad)
    ; (= (distance s10-tower-launchpad s10-antenna-1) 5)
    ; (= (distance s10-tower-launchpad s10-antenna-2) 5)
    ; (= (distance s10-tower-launchpad s10-antenna-3) 6)
    ; (= (distance s10-tower-launchpad s10-antenna-4) 6)
    ; (= (distance s10-tower-launchpad s10-antenna-5) 5)
    ; (= (distance s10-tower-launchpad s10-antenna-6) 5)

    ; (is-perspective dynamic-inspection360 s10-antenna-1)
    ; (is-perspective radiation-pattern s10-antenna-1)
    ; (is-perspective dock s10-antenna-1)
    ; (is-perspective front s10-antenna-1)
    ; (is-perspective above s10-antenna-1)
    ; (is-perspective below s10-antenna-1)
    ; (is-perspective left s10-antenna-1)
    ; (is-perspective right s10-antenna-1)
    ; (is-perspective front-below s10-antenna-1)
    ; (is-clear-perspective dynamic-inspection360 s10-antenna-1)
    ; (is-clear-perspective radiation-pattern s10-antenna-1)
    ; (is-clear-perspective front s10-antenna-1)
    ; (is-clear-perspective above s10-antenna-1)
    ; (is-clear-perspective below s10-antenna-1)
    ; (is-clear-perspective left s10-antenna-1)
    ; (is-clear-perspective right s10-antenna-1)
    ; (is-clear-perspective front-below s10-antenna-1)
    ; (= (distance s10-antenna-1 s10-tower-launchpad) 5)
    ; (= (distance s10-antenna-1 s10-antenna-2) 1)
    ; (= (distance s10-antenna-1 s10-antenna-3) 2)
    ; (= (distance s10-antenna-1 s10-antenna-4) 2)
    ; (= (distance s10-antenna-1 s10-antenna-5) 2)
    ; (= (distance s10-antenna-1 s10-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s10-antenna-2)
    ; (is-perspective radiation-pattern s10-antenna-2)
    ; (is-perspective dock s10-antenna-2)
    ; (is-perspective front s10-antenna-2)
    ; (is-perspective above s10-antenna-2)
    ; (is-perspective below s10-antenna-2)
    ; (is-perspective left s10-antenna-2)
    ; (is-perspective right s10-antenna-2)
    ; (is-perspective front-below s10-antenna-2)
    ; (is-clear-perspective dynamic-inspection360 s10-antenna-2)
    ; (is-clear-perspective radiation-pattern s10-antenna-2)
    ; (is-clear-perspective front s10-antenna-2)
    ; (is-clear-perspective above s10-antenna-2)
    ; (is-clear-perspective below s10-antenna-2)
    ; (is-clear-perspective left s10-antenna-2)
    ; (is-clear-perspective right s10-antenna-2)
    ; (is-clear-perspective front-below s10-antenna-2)
    ; (= (distance s10-antenna-2 s10-tower-launchpad) 5)
    ; (= (distance s10-antenna-2 s10-antenna-1) 1)
    ; (= (distance s10-antenna-2 s10-antenna-3) 2)
    ; (= (distance s10-antenna-2 s10-antenna-4) 2)
    ; (= (distance s10-antenna-2 s10-antenna-5) 2)
    ; (= (distance s10-antenna-2 s10-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s10-antenna-3)
    ; (is-perspective radiation-pattern s10-antenna-3)
    ; (is-perspective dock s10-antenna-3)
    ; (is-perspective front s10-antenna-3)
    ; (is-perspective above s10-antenna-3)
    ; (is-perspective below s10-antenna-3)
    ; (is-perspective left s10-antenna-3)
    ; (is-perspective right s10-antenna-3)
    ; (is-perspective front-below s10-antenna-3)
    ; (is-clear-perspective dynamic-inspection360 s10-antenna-3)
    ; (is-clear-perspective radiation-pattern s10-antenna-3)
    ; (is-clear-perspective front s10-antenna-3)
    ; (is-clear-perspective above s10-antenna-3)
    ; (is-clear-perspective below s10-antenna-3)
    ; (is-clear-perspective left s10-antenna-3)
    ; (is-clear-perspective right s10-antenna-3)
    ; (is-clear-perspective front-below s10-antenna-3)
    ; (= (distance s10-antenna-3 s10-tower-launchpad) 6)
    ; (= (distance s10-antenna-3 s10-antenna-1) 2)
    ; (= (distance s10-antenna-3 s10-antenna-2) 2)
    ; (= (distance s10-antenna-3 s10-antenna-4) 1)
    ; (= (distance s10-antenna-3 s10-antenna-5) 2)
    ; (= (distance s10-antenna-3 s10-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s10-antenna-4)
    ; (is-perspective radiation-pattern s10-antenna-4)
    ; (is-perspective dock s10-antenna-4)
    ; (is-perspective front s10-antenna-4)
    ; (is-perspective above s10-antenna-4)
    ; (is-perspective below s10-antenna-4)
    ; (is-perspective left s10-antenna-4)
    ; (is-perspective right s10-antenna-4)
    ; (is-perspective front-below s10-antenna-4)
    ; (is-clear-perspective dynamic-inspection360 s10-antenna-4)
    ; (is-clear-perspective radiation-pattern s10-antenna-4)
    ; (is-clear-perspective front s10-antenna-4)
    ; (is-clear-perspective above s10-antenna-4)
    ; (is-clear-perspective below s10-antenna-4)
    ; (is-clear-perspective left s10-antenna-4)
    ; (is-clear-perspective right s10-antenna-4)
    ; (is-clear-perspective front-below s10-antenna-4)
    ; (= (distance s10-antenna-4 s10-tower-launchpad) 6)
    ; (= (distance s10-antenna-4 s10-antenna-1) 2)
    ; (= (distance s10-antenna-4 s10-antenna-2) 2)
    ; (= (distance s10-antenna-4 s10-antenna-3) 1)
    ; (= (distance s10-antenna-4 s10-antenna-5) 2)
    ; (= (distance s10-antenna-4 s10-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s10-antenna-5)
    ; (is-perspective radiation-pattern s10-antenna-5)
    ; (is-perspective dock s10-antenna-5)
    ; (is-perspective front s10-antenna-5)
    ; (is-perspective above s10-antenna-5)
    ; (is-perspective below s10-antenna-5)
    ; (is-perspective left s10-antenna-5)
    ; (is-perspective right s10-antenna-5)
    ; (is-perspective front-below s10-antenna-5)
    ; (is-clear-perspective dynamic-inspection360 s10-antenna-5)
    ; (is-clear-perspective radiation-pattern s10-antenna-5)
    ; (is-clear-perspective front s10-antenna-5)
    ; (is-clear-perspective above s10-antenna-5)
    ; (is-clear-perspective below s10-antenna-5)
    ; (is-clear-perspective left s10-antenna-5)
    ; (is-clear-perspective right s10-antenna-5)
    ; (is-clear-perspective front-below s10-antenna-5)
    ; (= (distance s10-antenna-5 s10-tower-launchpad) 5)
    ; (= (distance s10-antenna-5 s10-antenna-1) 2)
    ; (= (distance s10-antenna-5 s10-antenna-2) 2)
    ; (= (distance s10-antenna-5 s10-antenna-3) 2)
    ; (= (distance s10-antenna-5 s10-antenna-4) 2)
    ; (= (distance s10-antenna-5 s10-antenna-6) 1)

    ; (is-perspective dynamic-inspection360 s10-antenna-6)
    ; (is-perspective radiation-pattern s10-antenna-6)
    ; (is-perspective dock s10-antenna-6)
    ; (is-perspective front s10-antenna-6)
    ; (is-perspective above s10-antenna-6)
    ; (is-perspective below s10-antenna-6)
    ; (is-perspective left s10-antenna-6)
    ; (is-perspective right s10-antenna-6)
    ; (is-perspective front-below s10-antenna-6)
    ; (is-clear-perspective dynamic-inspection360 s10-antenna-6)
    ; (is-clear-perspective radiation-pattern s10-antenna-6)
    ; (is-clear-perspective front s10-antenna-6)
    ; (is-clear-perspective above s10-antenna-6)
    ; (is-clear-perspective below s10-antenna-6)
    ; (is-clear-perspective left s10-antenna-6)
    ; (is-clear-perspective right s10-antenna-6)
    ; (is-clear-perspective front-below s10-antenna-6)
    ; (= (distance s10-antenna-6 s10-tower-launchpad) 5)
    ; (= (distance s10-antenna-6 s10-antenna-1) 2)
    ; (= (distance s10-antenna-6 s10-antenna-2) 2)
    ; (= (distance s10-antenna-6 s10-antenna-3) 2)
    ; (= (distance s10-antenna-6 s10-antenna-4) 2)
    ; (= (distance s10-antenna-6 s10-antenna-5) 1)

    ; (= (max-dock s10-tower-launchpad) 3) 
    ; (= (max-dock s10-antenna-1) 3)
    ; (= (max-dock s10-antenna-2) 3) 
    ; (= (max-dock s10-antenna-3) 3) 
    ; (= (max-dock s10-antenna-4) 3) 
    ; (= (max-dock s10-antenna-5) 3) 
    ; (= (max-dock s10-antenna-6) 3)

    ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ; ;s11-site

    ; (is-perspective launch-pad s11-tower-launchpad)
    ; ;(is-charging-dock s11-tower-launchpad launch-pad)
    ; (= (distance s11-tower-launchpad s11-antenna-1) 5)
    ; (= (distance s11-tower-launchpad s11-antenna-2) 5)
    ; (= (distance s11-tower-launchpad s11-antenna-3) 6)
    ; (= (distance s11-tower-launchpad s11-antenna-4) 6)
    ; (= (distance s11-tower-launchpad s11-antenna-5) 5)
    ; (= (distance s11-tower-launchpad s11-antenna-6) 5)

    ; (is-perspective dynamic-inspection360 s11-antenna-1)
    ; (is-perspective radiation-pattern s11-antenna-1)
    ; (is-perspective dock s11-antenna-1)
    ; (is-perspective front s11-antenna-1)
    ; (is-perspective above s11-antenna-1)
    ; (is-perspective below s11-antenna-1)
    ; (is-perspective left s11-antenna-1)
    ; (is-perspective right s11-antenna-1)
    ; (is-perspective front-below s11-antenna-1)
    ; (is-clear-perspective dynamic-inspection360 s11-antenna-1)
    ; (is-clear-perspective radiation-pattern s11-antenna-1)
    ; (is-clear-perspective front s11-antenna-1)
    ; (is-clear-perspective above s11-antenna-1)
    ; (is-clear-perspective below s11-antenna-1)
    ; (is-clear-perspective left s11-antenna-1)
    ; (is-clear-perspective right s11-antenna-1)
    ; (is-clear-perspective front-below s11-antenna-1)
    ; (= (distance s11-antenna-1 s11-tower-launchpad) 5)
    ; (= (distance s11-antenna-1 s11-antenna-2) 1)
    ; (= (distance s11-antenna-1 s11-antenna-3) 2)
    ; (= (distance s11-antenna-1 s11-antenna-4) 2)
    ; (= (distance s11-antenna-1 s11-antenna-5) 2)
    ; (= (distance s11-antenna-1 s11-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s11-antenna-2)
    ; (is-perspective radiation-pattern s11-antenna-2)
    ; (is-perspective dock s11-antenna-2)
    ; (is-perspective front s11-antenna-2)
    ; (is-perspective above s11-antenna-2)
    ; (is-perspective below s11-antenna-2)
    ; (is-perspective left s11-antenna-2)
    ; (is-perspective right s11-antenna-2)
    ; (is-perspective front-below s11-antenna-2)
    ; (is-clear-perspective dynamic-inspection360 s11-antenna-2)
    ; (is-clear-perspective radiation-pattern s11-antenna-2)
    ; (is-clear-perspective front s11-antenna-2)
    ; (is-clear-perspective above s11-antenna-2)
    ; (is-clear-perspective below s11-antenna-2)
    ; (is-clear-perspective left s11-antenna-2)
    ; (is-clear-perspective right s11-antenna-2)
    ; (is-clear-perspective front-below s11-antenna-2)
    ; (= (distance s11-antenna-2 s11-tower-launchpad) 5)
    ; (= (distance s11-antenna-2 s11-antenna-1) 1)
    ; (= (distance s11-antenna-2 s11-antenna-3) 2)
    ; (= (distance s11-antenna-2 s11-antenna-4) 2)
    ; (= (distance s11-antenna-2 s11-antenna-5) 2)
    ; (= (distance s11-antenna-2 s11-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s11-antenna-3)
    ; (is-perspective radiation-pattern s11-antenna-3)
    ; (is-perspective dock s11-antenna-3)
    ; (is-perspective front s11-antenna-3)
    ; (is-perspective above s11-antenna-3)
    ; (is-perspective below s11-antenna-3)
    ; (is-perspective left s11-antenna-3)
    ; (is-perspective right s11-antenna-3)
    ; (is-perspective front-below s11-antenna-3)
    ; (is-clear-perspective dynamic-inspection360 s11-antenna-3)
    ; (is-clear-perspective radiation-pattern s11-antenna-3)
    ; (is-clear-perspective front s11-antenna-3)
    ; (is-clear-perspective above s11-antenna-3)
    ; (is-clear-perspective below s11-antenna-3)
    ; (is-clear-perspective left s11-antenna-3)
    ; (is-clear-perspective right s11-antenna-3)
    ; (is-clear-perspective front-below s11-antenna-3)
    ; (= (distance s11-antenna-3 s11-tower-launchpad) 6)
    ; (= (distance s11-antenna-3 s11-antenna-1) 2)
    ; (= (distance s11-antenna-3 s11-antenna-2) 2)
    ; (= (distance s11-antenna-3 s11-antenna-4) 1)
    ; (= (distance s11-antenna-3 s11-antenna-5) 2)
    ; (= (distance s11-antenna-3 s11-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s11-antenna-4)
    ; (is-perspective radiation-pattern s11-antenna-4)
    ; (is-perspective dock s11-antenna-4)
    ; (is-perspective front s11-antenna-4)
    ; (is-perspective above s11-antenna-4)
    ; (is-perspective below s11-antenna-4)
    ; (is-perspective left s11-antenna-4)
    ; (is-perspective right s11-antenna-4)
    ; (is-perspective front-below s11-antenna-4)
    ; (is-clear-perspective dynamic-inspection360 s11-antenna-4)
    ; (is-clear-perspective radiation-pattern s11-antenna-4)
    ; (is-clear-perspective front s11-antenna-4)
    ; (is-clear-perspective above s11-antenna-4)
    ; (is-clear-perspective below s11-antenna-4)
    ; (is-clear-perspective left s11-antenna-4)
    ; (is-clear-perspective right s11-antenna-4)
    ; (is-clear-perspective front-below s11-antenna-4)
    ; (= (distance s11-antenna-4 s11-tower-launchpad) 6)
    ; (= (distance s11-antenna-4 s11-antenna-1) 2)
    ; (= (distance s11-antenna-4 s11-antenna-2) 2)
    ; (= (distance s11-antenna-4 s11-antenna-3) 1)
    ; (= (distance s11-antenna-4 s11-antenna-5) 2)
    ; (= (distance s11-antenna-4 s11-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s11-antenna-5)
    ; (is-perspective radiation-pattern s11-antenna-5)
    ; (is-perspective dock s11-antenna-5)
    ; (is-perspective front s11-antenna-5)
    ; (is-perspective above s11-antenna-5)
    ; (is-perspective below s11-antenna-5)
    ; (is-perspective left s11-antenna-5)
    ; (is-perspective right s11-antenna-5)
    ; (is-perspective front-below s11-antenna-5)
    ; (is-clear-perspective dynamic-inspection360 s11-antenna-5)
    ; (is-clear-perspective radiation-pattern s11-antenna-5)
    ; (is-clear-perspective front s11-antenna-5)
    ; (is-clear-perspective above s11-antenna-5)
    ; (is-clear-perspective below s11-antenna-5)
    ; (is-clear-perspective left s11-antenna-5)
    ; (is-clear-perspective right s11-antenna-5)
    ; (is-clear-perspective front-below s11-antenna-5)
    ; (= (distance s11-antenna-5 s11-tower-launchpad) 5)
    ; (= (distance s11-antenna-5 s11-antenna-1) 2)
    ; (= (distance s11-antenna-5 s11-antenna-2) 2)
    ; (= (distance s11-antenna-5 s11-antenna-3) 2)
    ; (= (distance s11-antenna-5 s11-antenna-4) 2)
    ; (= (distance s11-antenna-5 s11-antenna-6) 1)

    ; (is-perspective dynamic-inspection360 s11-antenna-6)
    ; (is-perspective radiation-pattern s11-antenna-6)
    ; (is-perspective dock s11-antenna-6)
    ; (is-perspective front s11-antenna-6)
    ; (is-perspective above s11-antenna-6)
    ; (is-perspective below s11-antenna-6)
    ; (is-perspective left s11-antenna-6)
    ; (is-perspective right s11-antenna-6)
    ; (is-perspective front-below s11-antenna-6)
    ; (is-clear-perspective dynamic-inspection360 s11-antenna-6)
    ; (is-clear-perspective radiation-pattern s11-antenna-6)
    ; (is-clear-perspective front s11-antenna-6)
    ; (is-clear-perspective above s11-antenna-6)
    ; (is-clear-perspective below s11-antenna-6)
    ; (is-clear-perspective left s11-antenna-6)
    ; (is-clear-perspective right s11-antenna-6)
    ; (is-clear-perspective front-below s11-antenna-6)
    ; (= (distance s11-antenna-6 s11-tower-launchpad) 5)
    ; (= (distance s11-antenna-6 s11-antenna-1) 2)
    ; (= (distance s11-antenna-6 s11-antenna-2) 2)
    ; (= (distance s11-antenna-6 s11-antenna-3) 2)
    ; (= (distance s11-antenna-6 s11-antenna-4) 2)
    ; (= (distance s11-antenna-6 s11-antenna-5) 1)

    ; (= (max-dock s11-tower-launchpad) 3) 
    ; (= (max-dock s11-antenna-1) 3)
    ; (= (max-dock s11-antenna-2) 3) 
    ; (= (max-dock s11-antenna-3) 3) 
    ; (= (max-dock s11-antenna-4) 3) 
    ; (= (max-dock s11-antenna-5) 3) 
    ; (= (max-dock s11-antenna-6) 3)

    ; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ; ;s12-site

    ; (is-perspective launch-pad s12-tower-launchpad)
    ; ;(is-charging-dock s12-tower-launchpad launch-pad)
    ; (= (distance s12-tower-launchpad s12-antenna-1) 5)
    ; (= (distance s12-tower-launchpad s12-antenna-2) 5)
    ; (= (distance s12-tower-launchpad s12-antenna-3) 6)
    ; (= (distance s12-tower-launchpad s12-antenna-4) 6)
    ; (= (distance s12-tower-launchpad s12-antenna-5) 5)
    ; (= (distance s12-tower-launchpad s12-antenna-6) 5)

    ; (is-perspective dynamic-inspection360 s12-antenna-1)
    ; (is-perspective radiation-pattern s12-antenna-1)
    ; (is-perspective dock s12-antenna-1)
    ; (is-perspective front s12-antenna-1)
    ; (is-perspective above s12-antenna-1)
    ; (is-perspective below s12-antenna-1)
    ; (is-perspective left s12-antenna-1)
    ; (is-perspective right s12-antenna-1)
    ; (is-perspective front-below s12-antenna-1)
    ; (is-clear-perspective dynamic-inspection360 s12-antenna-1)
    ; (is-clear-perspective radiation-pattern s12-antenna-1)
    ; (is-clear-perspective front s12-antenna-1)
    ; (is-clear-perspective above s12-antenna-1)
    ; (is-clear-perspective below s12-antenna-1)
    ; (is-clear-perspective left s12-antenna-1)
    ; (is-clear-perspective right s12-antenna-1)
    ; (is-clear-perspective front-below s12-antenna-1)
    ; (= (distance s12-antenna-1 s12-tower-launchpad) 5)
    ; (= (distance s12-antenna-1 s12-antenna-2) 1)
    ; (= (distance s12-antenna-1 s12-antenna-3) 2)
    ; (= (distance s12-antenna-1 s12-antenna-4) 2)
    ; (= (distance s12-antenna-1 s12-antenna-5) 2)
    ; (= (distance s12-antenna-1 s12-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s12-antenna-2)
    ; (is-perspective radiation-pattern s12-antenna-2)
    ; (is-perspective dock s12-antenna-2)
    ; (is-perspective front s12-antenna-2)
    ; (is-perspective above s12-antenna-2)
    ; (is-perspective below s12-antenna-2)
    ; (is-perspective left s12-antenna-2)
    ; (is-perspective right s12-antenna-2)
    ; (is-perspective front-below s12-antenna-2)
    ; (is-clear-perspective dynamic-inspection360 s12-antenna-2)
    ; (is-clear-perspective radiation-pattern s12-antenna-2)
    ; (is-clear-perspective front s12-antenna-2)
    ; (is-clear-perspective above s12-antenna-2)
    ; (is-clear-perspective below s12-antenna-2)
    ; (is-clear-perspective left s12-antenna-2)
    ; (is-clear-perspective right s12-antenna-2)
    ; (is-clear-perspective front-below s12-antenna-2)
    ; (= (distance s12-antenna-2 s12-tower-launchpad) 5)
    ; (= (distance s12-antenna-2 s12-antenna-1) 1)
    ; (= (distance s12-antenna-2 s12-antenna-3) 2)
    ; (= (distance s12-antenna-2 s12-antenna-4) 2)
    ; (= (distance s12-antenna-2 s12-antenna-5) 2)
    ; (= (distance s12-antenna-2 s12-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s12-antenna-3)
    ; (is-perspective radiation-pattern s12-antenna-3)
    ; (is-perspective dock s12-antenna-3)
    ; (is-perspective front s12-antenna-3)
    ; (is-perspective above s12-antenna-3)
    ; (is-perspective below s12-antenna-3)
    ; (is-perspective left s12-antenna-3)
    ; (is-perspective right s12-antenna-3)
    ; (is-perspective front-below s12-antenna-3)
    ; (is-clear-perspective dynamic-inspection360 s12-antenna-3)
    ; (is-clear-perspective radiation-pattern s12-antenna-3)
    ; (is-clear-perspective front s12-antenna-3)
    ; (is-clear-perspective above s12-antenna-3)
    ; (is-clear-perspective below s12-antenna-3)
    ; (is-clear-perspective left s12-antenna-3)
    ; (is-clear-perspective right s12-antenna-3)
    ; (is-clear-perspective front-below s12-antenna-3)
    ; (= (distance s12-antenna-3 s12-tower-launchpad) 6)
    ; (= (distance s12-antenna-3 s12-antenna-1) 2)
    ; (= (distance s12-antenna-3 s12-antenna-2) 2)
    ; (= (distance s12-antenna-3 s12-antenna-4) 1)
    ; (= (distance s12-antenna-3 s12-antenna-5) 2)
    ; (= (distance s12-antenna-3 s12-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s12-antenna-4)
    ; (is-perspective radiation-pattern s12-antenna-4)
    ; (is-perspective dock s12-antenna-4)
    ; (is-perspective front s12-antenna-4)
    ; (is-perspective above s12-antenna-4)
    ; (is-perspective below s12-antenna-4)
    ; (is-perspective left s12-antenna-4)
    ; (is-perspective right s12-antenna-4)
    ; (is-perspective front-below s12-antenna-4)
    ; (is-clear-perspective dynamic-inspection360 s12-antenna-4)
    ; (is-clear-perspective radiation-pattern s12-antenna-4)
    ; (is-clear-perspective front s12-antenna-4)
    ; (is-clear-perspective above s12-antenna-4)
    ; (is-clear-perspective below s12-antenna-4)
    ; (is-clear-perspective left s12-antenna-4)
    ; (is-clear-perspective right s12-antenna-4)
    ; (is-clear-perspective front-below s12-antenna-4)
    ; (= (distance s12-antenna-4 s12-tower-launchpad) 6)
    ; (= (distance s12-antenna-4 s12-antenna-1) 2)
    ; (= (distance s12-antenna-4 s12-antenna-2) 2)
    ; (= (distance s12-antenna-4 s12-antenna-3) 1)
    ; (= (distance s12-antenna-4 s12-antenna-5) 2)
    ; (= (distance s12-antenna-4 s12-antenna-6) 2)

    ; (is-perspective dynamic-inspection360 s12-antenna-5)
    ; (is-perspective radiation-pattern s12-antenna-5)
    ; (is-perspective dock s12-antenna-5)
    ; (is-perspective front s12-antenna-5)
    ; (is-perspective above s12-antenna-5)
    ; (is-perspective below s12-antenna-5)
    ; (is-perspective left s12-antenna-5)
    ; (is-perspective right s12-antenna-5)
    ; (is-perspective front-below s12-antenna-5)
    ; (is-clear-perspective dynamic-inspection360 s12-antenna-5)
    ; (is-clear-perspective radiation-pattern s12-antenna-5)
    ; (is-clear-perspective front s12-antenna-5)
    ; (is-clear-perspective above s12-antenna-5)
    ; (is-clear-perspective below s12-antenna-5)
    ; (is-clear-perspective left s12-antenna-5)
    ; (is-clear-perspective right s12-antenna-5)
    ; (is-clear-perspective front-below s12-antenna-5)
    ; (= (distance s12-antenna-5 s12-tower-launchpad) 5)
    ; (= (distance s12-antenna-5 s12-antenna-1) 2)
    ; (= (distance s12-antenna-5 s12-antenna-2) 2)
    ; (= (distance s12-antenna-5 s12-antenna-3) 2)
    ; (= (distance s12-antenna-5 s12-antenna-4) 2)
    ; (= (distance s12-antenna-5 s12-antenna-6) 1)

    ; (is-perspective dynamic-inspection360 s12-antenna-6)
    ; (is-perspective radiation-pattern s12-antenna-6)
    ; (is-perspective dock s12-antenna-6)
    ; (is-perspective front s12-antenna-6)
    ; (is-perspective above s12-antenna-6)
    ; (is-perspective below s12-antenna-6)
    ; (is-perspective left s12-antenna-6)
    ; (is-perspective right s12-antenna-6)
    ; (is-perspective front-below s12-antenna-6)
    ; (is-clear-perspective dynamic-inspection360 s12-antenna-6)
    ; (is-clear-perspective radiation-pattern s12-antenna-6)
    ; (is-clear-perspective front s12-antenna-6)
    ; (is-clear-perspective above s12-antenna-6)
    ; (is-clear-perspective below s12-antenna-6)
    ; (is-clear-perspective left s12-antenna-6)
    ; (is-clear-perspective right s12-antenna-6)
    ; (is-clear-perspective front-below s12-antenna-6)
    ; (= (distance s12-antenna-6 s12-tower-launchpad) 5)
    ; (= (distance s12-antenna-6 s12-antenna-1) 2)
    ; (= (distance s12-antenna-6 s12-antenna-2) 2)
    ; (= (distance s12-antenna-6 s12-antenna-3) 2)
    ; (= (distance s12-antenna-6 s12-antenna-4) 2)
    ; (= (distance s12-antenna-6 s12-antenna-5) 1)

    ; (= (max-dock s12-tower-launchpad) 3) 
    ; (= (max-dock s12-antenna-1) 3)
    ; (= (max-dock s12-antenna-2) 3) 
    ; (= (max-dock s12-antenna-3) 3) 
    ; (= (max-dock s12-antenna-4) 3) 
    ; (= (max-dock s12-antenna-5) 3) 
    ; (= (max-dock s12-antenna-6) 3)



    ;;;;;;;;;;;;;;;;;;;;;;;

    (is-available image front)
    (is-available thermal-image front)
    (is-available signal-measurement front)
    (is-available image above)
    (is-available thermal-image above)
    (is-available signal-measurement above)
    (is-available image below)
    (is-available thermal-image below)
    (is-available signal-measurement below)
    (is-available image left)
    (is-available thermal-image left)
    (is-available signal-measurement left)
    (is-available image right)
    (is-available thermal-image right)
    (is-available signal-measurement right)
    (is-available image front-below)
    (is-available thermal-image front-below)
    (is-available signal-measurement front-below)

    (is-available signal-measurement radiation-pattern)
    (is-available signal-measurement dynamic-inspection360)
    
    (is-dock launch-pad)
    (is-dock dock)

    ;(is-dynamic-inspection360 dynamic-inspection360)
    ;(is-radiation-pattern radiation-pattern) 

    (not_busy drone1)
    (not_busy drone2)
    (not_busy drone3)


    (has-capability drone1 camera);1
    (has-capability drone1 signal-measurer)
    (is-at drone1 s7-tower-launchpad launch-pad)
;    (is-at-component drone1 s7-tower-launchpad)
    (= (drone-charge drone1) 300)
    (= (max-charge-drone drone1) 300)
    (= (velocity drone1) 2)

    
    (has-capability drone2 thermal-camera);2
    (is-at drone2 s7-tower-launchpad launch-pad)
;    (is-at-component drone2 s7-tower-launchpad)
    (= (drone-charge drone2) 300)
    (= (max-charge-drone drone2) 300)
    (= (velocity drone2) 4)

    
    (has-capability drone3 signal-measurer);3
    (is-at drone3 s7-tower-launchpad launch-pad)
;    (is-at-component drone3 s7-tower-launchpad)
    (= (drone-charge drone3) 300)
    (= (max-charge-drone drone3) 300)
    (= (velocity drone3) 3)    



  )

  (:goal (and

    ;cluster goals
    (is-at drone1 s7-tower-launchpad launch-pad)
    (is-at drone2 s7-tower-launchpad launch-pad)
    (is-at drone3 s7-tower-launchpad launch-pad)

    ;inspection goals
    (know image s8-antenna-4 left)
    (know-simultaneous signal-measurement s8-antenna-2 radiation-pattern dynamic-inspection360)
    (know-simultaneous signal-measurement s8-antenna-1 radiation-pattern dynamic-inspection360)
    (know image s8-antenna-2 left)
    (know image s8-antenna-3 above)
    (know image s8-antenna-5 left)

    (know thermal-image s8-antenna-2 front)
    (know thermal-image s8-antenna-3 front-below)
    (know thermal-image s8-antenna-1 front)
    (know image s8-antenna-2 front-below)
    (know-simultaneous signal-measurement s8-antenna-5 radiation-pattern dynamic-inspection360)
    (know thermal-image s8-antenna-1 left)

    ; (know image s8-antenna-1 left)
    ; (know-simultaneous signal-measurement s8-antenna-3 radiation-pattern dynamic-inspection360)
    ; (know-simultaneous signal-measurement s8-antenna-4 radiation-pattern dynamic-inspection360)
    ; (know image s8-antenna-4 left)
    ; (know image s8-antenna-5 above)
    ; (know image s8-antenna-2 left)

    ; (know thermal-image s8-antenna-4 front)
    ; (know thermal-image s8-antenna-5 front-below)
    ; (know thermal-image s8-antenna-2 front)
    ; (know image s8-antenna-2 front-below)
    ; (know-simultaneous signal-measurement s8-antenna-4 radiation-pattern dynamic-inspection360)
    ; (know thermal-image s8-antenna-3 left)

    )
  )

  (:metric minimize (total-time))
)