; added a launchpad perspective for each drone
; added the is-clear-perspective for the relevant perspectives in the initial state



(define (problem asi-dur-problem-fullswap)
  (:domain asi-dur-domain-fullswap)
 
  (:objects 
	s1-tower-launchpad s1-antenna-1 s1-antenna-2 s1-antenna-3 s1-antenna-4 s1-antenna-5 s1-antenna-6 - component 
    s2-tower-launchpad s2-antenna-1 s2-antenna-2 s2-antenna-3 s2-antenna-4 s2-antenna-5 s2-antenna-6 - component 
    s3-tower-launchpad s3-antenna-1 s3-antenna-2 s3-antenna-3 s3-antenna-4 s3-antenna-5 s3-antenna-6 - component 
    charging-dock-1 charging-dock-2 - component 
    front above below left right front-below launch-pad dock radiation-pattern dynamic-inspection360 - perspective 
	drone1 drone2 - drone
	battery1 battery2 battery3 battery4 - battery 
    drone3 drone4 - drone
    battery5 battery6 battery7 battery8 - battery
  )

  (:init

    ;distance between sites

    (= (distance s1-tower-launchpad s2-tower-launchpad) 100)
    (= (distance s2-tower-launchpad s1-tower-launchpad) 100)

    (= (distance s1-tower-launchpad s3-tower-launchpad) 120)
    (= (distance s3-tower-launchpad s1-tower-launchpad) 120)

    (= (distance s2-tower-launchpad s3-tower-launchpad) 90)
    (= (distance s3-tower-launchpad s2-tower-launchpad) 90)

    (= (distance s1-tower-launchpad charging-dock-1) 60)
    (= (distance s2-tower-launchpad charging-dock-1) 60)
    (= (distance charging-dock-1 s1-tower-launchpad) 60)
    (= (distance charging-dock-1 s2-tower-launchpad) 60)

    (= (distance s1-tower-launchpad charging-dock-2) 150)
    (= (distance s2-tower-launchpad charging-dock-2) 80)
    (= (distance charging-dock-2 s1-tower-launchpad) 150)
    (= (distance charging-dock-2 s2-tower-launchpad) 80)

    (= (distance s3-tower-launchpad charging-dock-1) 80)
    (= (distance s3-tower-launchpad charging-dock-2) 40)
    (= (distance charging-dock-1 s3-tower-launchpad) 80)
    (= (distance charging-dock-2 s3-tower-launchpad) 40)

    (= (distance charging-dock-2 charging-dock-1) 110)
    (= (distance charging-dock-1 charging-dock-2) 110)

    ;connected-components between sites

    (connected-component s1-tower-launchpad s2-tower-launchpad)
    (connected-component s2-tower-launchpad s1-tower-launchpad)

    (connected-component s1-tower-launchpad s3-tower-launchpad)
    (connected-component s3-tower-launchpad s1-tower-launchpad)

    (connected-component s2-tower-launchpad s3-tower-launchpad)
    (connected-component s3-tower-launchpad s2-tower-launchpad)

    (connected-component s1-tower-launchpad charging-dock-1)
    (connected-component s2-tower-launchpad charging-dock-1)
    (connected-component charging-dock-1 s1-tower-launchpad)
    (connected-component charging-dock-1 s2-tower-launchpad)

    (connected-component s1-tower-launchpad charging-dock-2)
    (connected-component s2-tower-launchpad charging-dock-2)
    (connected-component charging-dock-2 s1-tower-launchpad)
    (connected-component charging-dock-2 s2-tower-launchpad)

    (connected-component s3-tower-launchpad charging-dock-1)
    (connected-component s3-tower-launchpad charging-dock-2)
    (connected-component charging-dock-1 s3-tower-launchpad)
    (connected-component charging-dock-2 s3-tower-launchpad)

    (connected-component charging-dock-2 charging-dock-1)
    (connected-component charging-dock-1 charging-dock-2)


    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;1st charging-dock

    (is-perspective launch-pad charging-dock-1)
    (is-charging-dock charging-dock-1 launch-pad)
    (= (max-dock charging-dock-1) 4)

    ;2nd charging-dock

    (is-perspective launch-pad charging-dock-2)
    (is-charging-dock charging-dock-2 launch-pad)
    (= (max-dock charging-dock-2) 4)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;first site

    (is-perspective launch-pad s1-tower-launchpad)
    (is-charging-dock s1-tower-launchpad launch-pad)
    (= (distance s1-tower-launchpad s1-antenna-1) 29)
    (= (distance s1-tower-launchpad s1-antenna-2) 29)
    (= (distance s1-tower-launchpad s1-antenna-3) 30)
    (= (distance s1-tower-launchpad s1-antenna-4) 30)
    (= (distance s1-tower-launchpad s1-antenna-5) 29)
    (= (distance s1-tower-launchpad s1-antenna-6) 29)

    (is-perspective dynamic-inspection360 s1-antenna-1)
    (is-perspective radiation-pattern s1-antenna-1)
    (is-perspective dock s1-antenna-1)
    (is-perspective front s1-antenna-1)
    (is-perspective above s1-antenna-1)
    (is-perspective below s1-antenna-1)
    (is-perspective left s1-antenna-1)
    (is-perspective right s1-antenna-1)
    (is-perspective front-below s1-antenna-1)
    (is-clear-perspective dynamic-inspection360 s1-antenna-1)
    (is-clear-perspective radiation-pattern s1-antenna-1)
    (is-clear-perspective front s1-antenna-1)
    (is-clear-perspective above s1-antenna-1)
    (is-clear-perspective below s1-antenna-1)
    (is-clear-perspective left s1-antenna-1)
    (is-clear-perspective right s1-antenna-1)
    (is-clear-perspective front-below s1-antenna-1)
    (= (distance s1-antenna-1 s1-tower-launchpad) 29)
    (= (distance s1-antenna-1 s1-antenna-2) 1)
    (= (distance s1-antenna-1 s1-antenna-3) 2)
    (= (distance s1-antenna-1 s1-antenna-4) 2)
    (= (distance s1-antenna-1 s1-antenna-5) 2)
    (= (distance s1-antenna-1 s1-antenna-6) 2)

    (is-perspective dynamic-inspection360 s1-antenna-2)
    (is-perspective radiation-pattern s1-antenna-2)
    (is-perspective dock s1-antenna-2)    
    (is-perspective front s1-antenna-2)
    (is-perspective above s1-antenna-2)
    (is-perspective below s1-antenna-2)
    (is-perspective left s1-antenna-2)
    (is-perspective right s1-antenna-2)
    (is-perspective front-below s1-antenna-2)
    (is-clear-perspective dynamic-inspection360 s1-antenna-2)
    (is-clear-perspective radiation-pattern s1-antenna-2)
    (is-clear-perspective front s1-antenna-2)
    (is-clear-perspective above s1-antenna-2)
    (is-clear-perspective below s1-antenna-2)
    (is-clear-perspective left s1-antenna-2)
    (is-clear-perspective right s1-antenna-2)
    (is-clear-perspective front-below s1-antenna-2)
    (= (distance s1-antenna-2 s1-tower-launchpad) 29)
    (= (distance s1-antenna-2 s1-antenna-1) 1)
    (= (distance s1-antenna-2 s1-antenna-3) 2)
    (= (distance s1-antenna-2 s1-antenna-4) 2)
    (= (distance s1-antenna-2 s1-antenna-5) 2)
    (= (distance s1-antenna-2 s1-antenna-6) 2)

    (is-perspective dynamic-inspection360 s1-antenna-3)
    (is-perspective radiation-pattern s1-antenna-3)
    (is-perspective dock s1-antenna-3)
    (is-perspective front s1-antenna-3)
    (is-perspective above s1-antenna-3)
    (is-perspective below s1-antenna-3)
    (is-perspective left s1-antenna-3)
    (is-perspective right s1-antenna-3)
    (is-perspective front-below s1-antenna-3)
    (is-clear-perspective dynamic-inspection360 s1-antenna-3)
    (is-clear-perspective radiation-pattern s1-antenna-3)
    (is-clear-perspective front s1-antenna-3)
    (is-clear-perspective above s1-antenna-3)
    (is-clear-perspective below s1-antenna-3)
    (is-clear-perspective left s1-antenna-3)
    (is-clear-perspective right s1-antenna-3)
    (is-clear-perspective front-below s1-antenna-3)
    (= (distance s1-antenna-3 s1-tower-launchpad) 30)
    (= (distance s1-antenna-3 s1-antenna-1) 2)
    (= (distance s1-antenna-3 s1-antenna-2) 2)
    (= (distance s1-antenna-3 s1-antenna-4) 1)
    (= (distance s1-antenna-3 s1-antenna-5) 2)
    (= (distance s1-antenna-3 s1-antenna-6) 2)

    (is-perspective dynamic-inspection360 s1-antenna-4)
    (is-perspective radiation-pattern s1-antenna-4)
    (is-perspective dock s1-antenna-4)
    (is-perspective front s1-antenna-4)
    (is-perspective above s1-antenna-4)
    (is-perspective below s1-antenna-4)
    (is-perspective left s1-antenna-4)
    (is-perspective right s1-antenna-4)
    (is-perspective front-below s1-antenna-4)
    (is-clear-perspective dynamic-inspection360 s1-antenna-4)
    (is-clear-perspective radiation-pattern s1-antenna-4)
    (is-clear-perspective front s1-antenna-4)
    (is-clear-perspective above s1-antenna-4)
    (is-clear-perspective below s1-antenna-4)
    (is-clear-perspective left s1-antenna-4)
    (is-clear-perspective right s1-antenna-4)
    (is-clear-perspective front-below s1-antenna-4)
    (= (distance s1-antenna-4 s1-tower-launchpad) 30)
    (= (distance s1-antenna-4 s1-antenna-1) 2)
    (= (distance s1-antenna-4 s1-antenna-2) 2)
    (= (distance s1-antenna-4 s1-antenna-3) 1)
    (= (distance s1-antenna-4 s1-antenna-5) 2)
    (= (distance s1-antenna-4 s1-antenna-6) 2)

    (is-perspective dynamic-inspection360 s1-antenna-5)
    (is-perspective radiation-pattern s1-antenna-5)
    (is-perspective dock s1-antenna-5)
    (is-perspective front s1-antenna-5)
    (is-perspective above s1-antenna-5)
    (is-perspective below s1-antenna-5)
    (is-perspective left s1-antenna-5)
    (is-perspective right s1-antenna-5)
    (is-perspective front-below s1-antenna-5)
    (is-clear-perspective dynamic-inspection360 s1-antenna-5)
    (is-clear-perspective radiation-pattern s1-antenna-5)
    (is-clear-perspective front s1-antenna-5)
    (is-clear-perspective above s1-antenna-5)
    (is-clear-perspective below s1-antenna-5)
    (is-clear-perspective left s1-antenna-5)
    (is-clear-perspective right s1-antenna-5)
    (is-clear-perspective front-below s1-antenna-5)
    (= (distance s1-antenna-5 s1-tower-launchpad) 29)
    (= (distance s1-antenna-5 s1-antenna-1) 2)
    (= (distance s1-antenna-5 s1-antenna-2) 2)
    (= (distance s1-antenna-5 s1-antenna-3) 2)
    (= (distance s1-antenna-5 s1-antenna-4) 2)
    (= (distance s1-antenna-5 s1-antenna-6) 1)

    (is-perspective dynamic-inspection360 s1-antenna-6)
    (is-perspective radiation-pattern s1-antenna-6)
    (is-perspective dock s1-antenna-6)
    (is-perspective front s1-antenna-6)
    (is-perspective above s1-antenna-6)
    (is-perspective below s1-antenna-6)
    (is-perspective left s1-antenna-6)
    (is-perspective right s1-antenna-6)
    (is-perspective front-below s1-antenna-6)
    (is-clear-perspective dynamic-inspection360 s1-antenna-6)
    (is-clear-perspective radiation-pattern s1-antenna-6)
    (is-clear-perspective front s1-antenna-6)
    (is-clear-perspective above s1-antenna-6)
    (is-clear-perspective below s1-antenna-6)
    (is-clear-perspective left s1-antenna-6)
    (is-clear-perspective right s1-antenna-6)
    (is-clear-perspective front-below s1-antenna-6)
    (= (distance s1-antenna-6 s1-tower-launchpad) 29)
    (= (distance s1-antenna-6 s1-antenna-1) 2)
    (= (distance s1-antenna-6 s1-antenna-2) 2)
    (= (distance s1-antenna-6 s1-antenna-3) 2)
    (= (distance s1-antenna-6 s1-antenna-4) 2)
    (= (distance s1-antenna-6 s1-antenna-5) 1)

    (connected-component s1-tower-launchpad s1-antenna-1)
    (connected-component s1-tower-launchpad s1-antenna-2)
    (connected-component s1-tower-launchpad s1-antenna-3)
    (connected-component s1-tower-launchpad s1-antenna-4)
    (connected-component s1-tower-launchpad s1-antenna-5)
    (connected-component s1-tower-launchpad s1-antenna-6)

    (connected-component s1-antenna-1 s1-tower-launchpad)
    (connected-component s1-antenna-1 s1-antenna-2)
    (connected-component s1-antenna-1 s1-antenna-3)
    (connected-component s1-antenna-1 s1-antenna-4)
    (connected-component s1-antenna-1 s1-antenna-5)
    (connected-component s1-antenna-1 s1-antenna-6)

    (connected-component s1-antenna-2 s1-tower-launchpad)
    (connected-component s1-antenna-2 s1-antenna-1)
    (connected-component s1-antenna-2 s1-antenna-3)
    (connected-component s1-antenna-2 s1-antenna-4)
    (connected-component s1-antenna-2 s1-antenna-5)
    (connected-component s1-antenna-2 s1-antenna-6)

    (connected-component s1-antenna-3 s1-tower-launchpad)
    (connected-component s1-antenna-3 s1-antenna-1)
    (connected-component s1-antenna-3 s1-antenna-2)
    (connected-component s1-antenna-3 s1-antenna-4)
    (connected-component s1-antenna-3 s1-antenna-5)
    (connected-component s1-antenna-3 s1-antenna-6)

    (connected-component s1-antenna-4 s1-tower-launchpad)
    (connected-component s1-antenna-4 s1-antenna-1)
    (connected-component s1-antenna-4 s1-antenna-2)
    (connected-component s1-antenna-4 s1-antenna-3)
    (connected-component s1-antenna-4 s1-antenna-5)
    (connected-component s1-antenna-4 s1-antenna-6)

    (connected-component s1-antenna-5 s1-tower-launchpad)
    (connected-component s1-antenna-5 s1-antenna-1)
    (connected-component s1-antenna-5 s1-antenna-2)
    (connected-component s1-antenna-5 s1-antenna-3)
    (connected-component s1-antenna-5 s1-antenna-4)
    (connected-component s1-antenna-5 s1-antenna-6)

    (connected-component s1-antenna-6 s1-tower-launchpad)
    (connected-component s1-antenna-6 s1-antenna-1)
    (connected-component s1-antenna-6 s1-antenna-2)
    (connected-component s1-antenna-6 s1-antenna-3)
    (connected-component s1-antenna-6 s1-antenna-4)
    (connected-component s1-antenna-6 s1-antenna-5)

    (= (max-dock s1-tower-launchpad) 0) 
    (= (max-dock s1-antenna-1) 3)
    (= (max-dock s1-antenna-2) 3) 
    (= (max-dock s1-antenna-3) 3) 
    (= (max-dock s1-antenna-4) 3) 
    (= (max-dock s1-antenna-5) 3) 
    (= (max-dock s1-antenna-6) 3)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;second site

    (is-perspective launch-pad s2-tower-launchpad)
    (is-charging-dock s2-tower-launchpad launch-pad)
    (= (distance s2-tower-launchpad s2-antenna-1) 29)
    (= (distance s2-tower-launchpad s2-antenna-2) 29)
    (= (distance s2-tower-launchpad s2-antenna-3) 30)
    (= (distance s2-tower-launchpad s2-antenna-4) 30)
    (= (distance s2-tower-launchpad s2-antenna-5) 29)
    (= (distance s2-tower-launchpad s2-antenna-6) 29)

    (is-perspective dynamic-inspection360 s2-antenna-1)
    (is-perspective radiation-pattern s2-antenna-1)
    (is-perspective dock s2-antenna-1)
    (is-perspective front s2-antenna-1)
    (is-perspective above s2-antenna-1)
    (is-perspective below s2-antenna-1)
    (is-perspective left s2-antenna-1)
    (is-perspective right s2-antenna-1)
    (is-perspective front-below s2-antenna-1)
    (is-clear-perspective dynamic-inspection360 s2-antenna-1)
    (is-clear-perspective radiation-pattern s2-antenna-1)
    (is-clear-perspective front s2-antenna-1)
    (is-clear-perspective above s2-antenna-1)
    (is-clear-perspective below s2-antenna-1)
    (is-clear-perspective left s2-antenna-1)
    (is-clear-perspective right s2-antenna-1)
    (is-clear-perspective front-below s2-antenna-1)
    (= (distance s2-antenna-1 s2-tower-launchpad) 29)
    (= (distance s2-antenna-1 s2-antenna-2) 1)
    (= (distance s2-antenna-1 s2-antenna-3) 2)
    (= (distance s2-antenna-1 s2-antenna-4) 2)
    (= (distance s2-antenna-1 s2-antenna-5) 2)
    (= (distance s2-antenna-1 s2-antenna-6) 2)

    (is-perspective dynamic-inspection360 s2-antenna-2)
    (is-perspective radiation-pattern s2-antenna-2)
    (is-perspective dock s2-antenna-2)    
    (is-perspective front s2-antenna-2)
    (is-perspective above s2-antenna-2)
    (is-perspective below s2-antenna-2)
    (is-perspective left s2-antenna-2)
    (is-perspective right s2-antenna-2)
    (is-perspective front-below s2-antenna-2)
    (is-clear-perspective dynamic-inspection360 s2-antenna-2)
    (is-clear-perspective radiation-pattern s2-antenna-2)
    (is-clear-perspective front s2-antenna-2)
    (is-clear-perspective above s2-antenna-2)
    (is-clear-perspective below s2-antenna-2)
    (is-clear-perspective left s2-antenna-2)
    (is-clear-perspective right s2-antenna-2)
    (is-clear-perspective front-below s2-antenna-2)
    (= (distance s2-antenna-2 s2-tower-launchpad) 29)
    (= (distance s2-antenna-2 s2-antenna-1) 1)
    (= (distance s2-antenna-2 s2-antenna-3) 2)
    (= (distance s2-antenna-2 s2-antenna-4) 2)
    (= (distance s2-antenna-2 s2-antenna-5) 2)
    (= (distance s2-antenna-2 s2-antenna-6) 2)

    (is-perspective dynamic-inspection360 s2-antenna-3)
    (is-perspective radiation-pattern s2-antenna-3)
    (is-perspective dock s2-antenna-3)
    (is-perspective front s2-antenna-3)
    (is-perspective above s2-antenna-3)
    (is-perspective below s2-antenna-3)
    (is-perspective left s2-antenna-3)
    (is-perspective right s2-antenna-3)
    (is-perspective front-below s2-antenna-3)
    (is-clear-perspective dynamic-inspection360 s2-antenna-3)
    (is-clear-perspective radiation-pattern s2-antenna-3)
    (is-clear-perspective front s2-antenna-3)
    (is-clear-perspective above s2-antenna-3)
    (is-clear-perspective below s2-antenna-3)
    (is-clear-perspective left s2-antenna-3)
    (is-clear-perspective right s2-antenna-3)
    (is-clear-perspective front-below s2-antenna-3)
    (= (distance s2-antenna-3 s2-tower-launchpad) 30)
    (= (distance s2-antenna-3 s2-antenna-1) 2)
    (= (distance s2-antenna-3 s2-antenna-2) 2)
    (= (distance s2-antenna-3 s2-antenna-4) 1)
    (= (distance s2-antenna-3 s2-antenna-5) 2)
    (= (distance s2-antenna-3 s2-antenna-6) 2)

    (is-perspective dynamic-inspection360 s2-antenna-4)
    (is-perspective radiation-pattern s2-antenna-4)
    (is-perspective dock s2-antenna-4)
    (is-perspective front s2-antenna-4)
    (is-perspective above s2-antenna-4)
    (is-perspective below s2-antenna-4)
    (is-perspective left s2-antenna-4)
    (is-perspective right s2-antenna-4)
    (is-perspective front-below s2-antenna-4)
    (is-clear-perspective dynamic-inspection360 s2-antenna-4)
    (is-clear-perspective radiation-pattern s2-antenna-4)
    (is-clear-perspective front s2-antenna-4)
    (is-clear-perspective above s2-antenna-4)
    (is-clear-perspective below s2-antenna-4)
    (is-clear-perspective left s2-antenna-4)
    (is-clear-perspective right s2-antenna-4)
    (is-clear-perspective front-below s2-antenna-4)
    (= (distance s2-antenna-4 s2-tower-launchpad) 30)
    (= (distance s2-antenna-4 s2-antenna-1) 2)
    (= (distance s2-antenna-4 s2-antenna-2) 2)
    (= (distance s2-antenna-4 s2-antenna-3) 1)
    (= (distance s2-antenna-4 s2-antenna-5) 2)
    (= (distance s2-antenna-4 s2-antenna-6) 2)

    (is-perspective dynamic-inspection360 s2-antenna-5)
    (is-perspective radiation-pattern s2-antenna-5)
    (is-perspective dock s2-antenna-5)
    (is-perspective front s2-antenna-5)
    (is-perspective above s2-antenna-5)
    (is-perspective below s2-antenna-5)
    (is-perspective left s2-antenna-5)
    (is-perspective right s2-antenna-5)
    (is-perspective front-below s2-antenna-5)
    (is-clear-perspective dynamic-inspection360 s2-antenna-5)
    (is-clear-perspective radiation-pattern s2-antenna-5)
    (is-clear-perspective front s2-antenna-5)
    (is-clear-perspective above s2-antenna-5)
    (is-clear-perspective below s2-antenna-5)
    (is-clear-perspective left s2-antenna-5)
    (is-clear-perspective right s2-antenna-5)
    (is-clear-perspective front-below s2-antenna-5)
    (= (distance s2-antenna-5 s2-tower-launchpad) 29)
    (= (distance s2-antenna-5 s2-antenna-1) 2)
    (= (distance s2-antenna-5 s2-antenna-2) 2)
    (= (distance s2-antenna-5 s2-antenna-3) 2)
    (= (distance s2-antenna-5 s2-antenna-4) 2)
    (= (distance s2-antenna-5 s2-antenna-6) 1)

    (is-perspective dynamic-inspection360 s2-antenna-6)
    (is-perspective radiation-pattern s2-antenna-6)
    (is-perspective dock s2-antenna-6)
    (is-perspective front s2-antenna-6)
    (is-perspective above s2-antenna-6)
    (is-perspective below s2-antenna-6)
    (is-perspective left s2-antenna-6)
    (is-perspective right s2-antenna-6)
    (is-perspective front-below s2-antenna-6)
    (is-clear-perspective dynamic-inspection360 s2-antenna-6)
    (is-clear-perspective radiation-pattern s2-antenna-6)
    (is-clear-perspective front s2-antenna-6)
    (is-clear-perspective above s2-antenna-6)
    (is-clear-perspective below s2-antenna-6)
    (is-clear-perspective left s2-antenna-6)
    (is-clear-perspective right s2-antenna-6)
    (is-clear-perspective front-below s2-antenna-6)
    (= (distance s2-antenna-6 s2-tower-launchpad) 29)
    (= (distance s2-antenna-6 s2-antenna-1) 2)
    (= (distance s2-antenna-6 s2-antenna-2) 2)
    (= (distance s2-antenna-6 s2-antenna-3) 2)
    (= (distance s2-antenna-6 s2-antenna-4) 2)
    (= (distance s2-antenna-6 s2-antenna-5) 1)

    (connected-component s2-tower-launchpad s2-antenna-1)
    (connected-component s2-tower-launchpad s2-antenna-2)
    (connected-component s2-tower-launchpad s2-antenna-3)
    (connected-component s2-tower-launchpad s2-antenna-4)
    (connected-component s2-tower-launchpad s2-antenna-5)
    (connected-component s2-tower-launchpad s2-antenna-6)

    (connected-component s2-antenna-1 s2-tower-launchpad)
    (connected-component s2-antenna-1 s2-antenna-2)
    (connected-component s2-antenna-1 s2-antenna-3)
    (connected-component s2-antenna-1 s2-antenna-4)
    (connected-component s2-antenna-1 s2-antenna-5)
    (connected-component s2-antenna-1 s2-antenna-6)

    (connected-component s2-antenna-2 s2-tower-launchpad)
    (connected-component s2-antenna-2 s2-antenna-1)
    (connected-component s2-antenna-2 s2-antenna-3)
    (connected-component s2-antenna-2 s2-antenna-4)
    (connected-component s2-antenna-2 s2-antenna-5)
    (connected-component s2-antenna-2 s2-antenna-6)

    (connected-component s2-antenna-3 s2-tower-launchpad)
    (connected-component s2-antenna-3 s2-antenna-1)
    (connected-component s2-antenna-3 s2-antenna-2)
    (connected-component s2-antenna-3 s2-antenna-4)
    (connected-component s2-antenna-3 s2-antenna-5)
    (connected-component s2-antenna-3 s2-antenna-6)

    (connected-component s2-antenna-4 s2-tower-launchpad)
    (connected-component s2-antenna-4 s2-antenna-1)
    (connected-component s2-antenna-4 s2-antenna-2)
    (connected-component s2-antenna-4 s2-antenna-3)
    (connected-component s2-antenna-4 s2-antenna-5)
    (connected-component s2-antenna-4 s2-antenna-6)

    (connected-component s2-antenna-5 s2-tower-launchpad)
    (connected-component s2-antenna-5 s2-antenna-1)
    (connected-component s2-antenna-5 s2-antenna-2)
    (connected-component s2-antenna-5 s2-antenna-3)
    (connected-component s2-antenna-5 s2-antenna-4)
    (connected-component s2-antenna-5 s2-antenna-6)

    (connected-component s2-antenna-6 s2-tower-launchpad)
    (connected-component s2-antenna-6 s2-antenna-1)
    (connected-component s2-antenna-6 s2-antenna-2)
    (connected-component s2-antenna-6 s2-antenna-3)
    (connected-component s2-antenna-6 s2-antenna-4)
    (connected-component s2-antenna-6 s2-antenna-5)

    (= (max-dock s2-tower-launchpad) 4) 
    (= (max-dock s2-antenna-1) 3)
    (= (max-dock s2-antenna-2) 3) 
    (= (max-dock s2-antenna-3) 3) 
    (= (max-dock s2-antenna-4) 3) 
    (= (max-dock s2-antenna-5) 3) 
    (= (max-dock s2-antenna-6) 3)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;third site

    (is-perspective launch-pad s3-tower-launchpad)
    (is-charging-dock s3-tower-launchpad launch-pad)
    (= (distance s3-tower-launchpad s3-antenna-1) 29)
    (= (distance s3-tower-launchpad s3-antenna-2) 29)
    (= (distance s3-tower-launchpad s3-antenna-3) 30)
    (= (distance s3-tower-launchpad s3-antenna-4) 30)
    (= (distance s3-tower-launchpad s3-antenna-5) 29)
    (= (distance s3-tower-launchpad s3-antenna-6) 29)

    (is-perspective dynamic-inspection360 s3-antenna-1)
    (is-perspective radiation-pattern s3-antenna-1)
    (is-perspective dock s3-antenna-1)
    (is-perspective front s3-antenna-1)
    (is-perspective above s3-antenna-1)
    (is-perspective below s3-antenna-1)
    (is-perspective left s3-antenna-1)
    (is-perspective right s3-antenna-1)
    (is-perspective front-below s3-antenna-1)
    (is-clear-perspective dynamic-inspection360 s3-antenna-1)
    (is-clear-perspective radiation-pattern s3-antenna-1)
    (is-clear-perspective front s3-antenna-1)
    (is-clear-perspective above s3-antenna-1)
    (is-clear-perspective below s3-antenna-1)
    (is-clear-perspective left s3-antenna-1)
    (is-clear-perspective right s3-antenna-1)
    (is-clear-perspective front-below s3-antenna-1)
    (= (distance s3-antenna-1 s3-tower-launchpad) 29)
    (= (distance s3-antenna-1 s3-antenna-2) 1)
    (= (distance s3-antenna-1 s3-antenna-3) 2)
    (= (distance s3-antenna-1 s3-antenna-4) 2)
    (= (distance s3-antenna-1 s3-antenna-5) 2)
    (= (distance s3-antenna-1 s3-antenna-6) 2)

    (is-perspective dynamic-inspection360 s3-antenna-2)
    (is-perspective radiation-pattern s3-antenna-2)
    (is-perspective dock s3-antenna-2)    
    (is-perspective front s3-antenna-2)
    (is-perspective above s3-antenna-2)
    (is-perspective below s3-antenna-2)
    (is-perspective left s3-antenna-2)
    (is-perspective right s3-antenna-2)
    (is-perspective front-below s3-antenna-2)
    (is-clear-perspective dynamic-inspection360 s3-antenna-2)
    (is-clear-perspective radiation-pattern s3-antenna-2)
    (is-clear-perspective front s3-antenna-2)
    (is-clear-perspective above s3-antenna-2)
    (is-clear-perspective below s3-antenna-2)
    (is-clear-perspective left s3-antenna-2)
    (is-clear-perspective right s3-antenna-2)
    (is-clear-perspective front-below s3-antenna-2)
    (= (distance s3-antenna-2 s3-tower-launchpad) 29)
    (= (distance s3-antenna-2 s3-antenna-1) 1)
    (= (distance s3-antenna-2 s3-antenna-3) 2)
    (= (distance s3-antenna-2 s3-antenna-4) 2)
    (= (distance s3-antenna-2 s3-antenna-5) 2)
    (= (distance s3-antenna-2 s3-antenna-6) 2)

    (is-perspective dynamic-inspection360 s3-antenna-3)
    (is-perspective radiation-pattern s3-antenna-3)
    (is-perspective dock s3-antenna-3)
    (is-perspective front s3-antenna-3)
    (is-perspective above s3-antenna-3)
    (is-perspective below s3-antenna-3)
    (is-perspective left s3-antenna-3)
    (is-perspective right s3-antenna-3)
    (is-perspective front-below s3-antenna-3)
    (is-clear-perspective dynamic-inspection360 s3-antenna-3)
    (is-clear-perspective radiation-pattern s3-antenna-3)
    (is-clear-perspective front s3-antenna-3)
    (is-clear-perspective above s3-antenna-3)
    (is-clear-perspective below s3-antenna-3)
    (is-clear-perspective left s3-antenna-3)
    (is-clear-perspective right s3-antenna-3)
    (is-clear-perspective front-below s3-antenna-3)
    (= (distance s3-antenna-3 s3-tower-launchpad) 30)
    (= (distance s3-antenna-3 s3-antenna-1) 2)
    (= (distance s3-antenna-3 s3-antenna-2) 2)
    (= (distance s3-antenna-3 s3-antenna-4) 1)
    (= (distance s3-antenna-3 s3-antenna-5) 2)
    (= (distance s3-antenna-3 s3-antenna-6) 2)

    (is-perspective dynamic-inspection360 s3-antenna-4)
    (is-perspective radiation-pattern s3-antenna-4)
    (is-perspective dock s3-antenna-4)
    (is-perspective front s3-antenna-4)
    (is-perspective above s3-antenna-4)
    (is-perspective below s3-antenna-4)
    (is-perspective left s3-antenna-4)
    (is-perspective right s3-antenna-4)
    (is-perspective front-below s3-antenna-4)
    (is-clear-perspective dynamic-inspection360 s3-antenna-4)
    (is-clear-perspective radiation-pattern s3-antenna-4)
    (is-clear-perspective front s3-antenna-4)
    (is-clear-perspective above s3-antenna-4)
    (is-clear-perspective below s3-antenna-4)
    (is-clear-perspective left s3-antenna-4)
    (is-clear-perspective right s3-antenna-4)
    (is-clear-perspective front-below s3-antenna-4)
    (= (distance s3-antenna-4 s3-tower-launchpad) 30)
    (= (distance s3-antenna-4 s3-antenna-1) 2)
    (= (distance s3-antenna-4 s3-antenna-2) 2)
    (= (distance s3-antenna-4 s3-antenna-3) 1)
    (= (distance s3-antenna-4 s3-antenna-5) 2)
    (= (distance s3-antenna-4 s3-antenna-6) 2)

    (is-perspective dynamic-inspection360 s3-antenna-5)
    (is-perspective radiation-pattern s3-antenna-5)
    (is-perspective dock s3-antenna-5)
    (is-perspective front s3-antenna-5)
    (is-perspective above s3-antenna-5)
    (is-perspective below s3-antenna-5)
    (is-perspective left s3-antenna-5)
    (is-perspective right s3-antenna-5)
    (is-perspective front-below s3-antenna-5)
    (is-clear-perspective dynamic-inspection360 s3-antenna-5)
    (is-clear-perspective radiation-pattern s3-antenna-5)
    (is-clear-perspective front s3-antenna-5)
    (is-clear-perspective above s3-antenna-5)
    (is-clear-perspective below s3-antenna-5)
    (is-clear-perspective left s3-antenna-5)
    (is-clear-perspective right s3-antenna-5)
    (is-clear-perspective front-below s3-antenna-5)
    (= (distance s3-antenna-5 s3-tower-launchpad) 29)
    (= (distance s3-antenna-5 s3-antenna-1) 2)
    (= (distance s3-antenna-5 s3-antenna-2) 2)
    (= (distance s3-antenna-5 s3-antenna-3) 2)
    (= (distance s3-antenna-5 s3-antenna-4) 2)
    (= (distance s3-antenna-5 s3-antenna-6) 1)

    (is-perspective dynamic-inspection360 s3-antenna-6)
    (is-perspective radiation-pattern s3-antenna-6)
    (is-perspective dock s3-antenna-6)
    (is-perspective front s3-antenna-6)
    (is-perspective above s3-antenna-6)
    (is-perspective below s3-antenna-6)
    (is-perspective left s3-antenna-6)
    (is-perspective right s3-antenna-6)
    (is-perspective front-below s3-antenna-6)
    (is-clear-perspective dynamic-inspection360 s3-antenna-6)
    (is-clear-perspective radiation-pattern s3-antenna-6)
    (is-clear-perspective front s3-antenna-6)
    (is-clear-perspective above s3-antenna-6)
    (is-clear-perspective below s3-antenna-6)
    (is-clear-perspective left s3-antenna-6)
    (is-clear-perspective right s3-antenna-6)
    (is-clear-perspective front-below s3-antenna-6)
    (= (distance s3-antenna-6 s3-tower-launchpad) 29)
    (= (distance s3-antenna-6 s3-antenna-1) 2)
    (= (distance s3-antenna-6 s3-antenna-2) 2)
    (= (distance s3-antenna-6 s3-antenna-3) 2)
    (= (distance s3-antenna-6 s3-antenna-4) 2)
    (= (distance s3-antenna-6 s3-antenna-5) 1)

    (connected-component s3-tower-launchpad s3-antenna-1)
    (connected-component s3-tower-launchpad s3-antenna-2)
    (connected-component s3-tower-launchpad s3-antenna-3)
    (connected-component s3-tower-launchpad s3-antenna-4)
    (connected-component s3-tower-launchpad s3-antenna-5)
    (connected-component s3-tower-launchpad s3-antenna-6)

    (connected-component s3-antenna-1 s3-tower-launchpad)
    (connected-component s3-antenna-1 s3-antenna-2)
    (connected-component s3-antenna-1 s3-antenna-3)
    (connected-component s3-antenna-1 s3-antenna-4)
    (connected-component s3-antenna-1 s3-antenna-5)
    (connected-component s3-antenna-1 s3-antenna-6)

    (connected-component s3-antenna-2 s3-tower-launchpad)
    (connected-component s3-antenna-2 s3-antenna-1)
    (connected-component s3-antenna-2 s3-antenna-3)
    (connected-component s3-antenna-2 s3-antenna-4)
    (connected-component s3-antenna-2 s3-antenna-5)
    (connected-component s3-antenna-2 s3-antenna-6)

    (connected-component s3-antenna-3 s3-tower-launchpad)
    (connected-component s3-antenna-3 s3-antenna-1)
    (connected-component s3-antenna-3 s3-antenna-2)
    (connected-component s3-antenna-3 s3-antenna-4)
    (connected-component s3-antenna-3 s3-antenna-5)
    (connected-component s3-antenna-3 s3-antenna-6)

    (connected-component s3-antenna-4 s3-tower-launchpad)
    (connected-component s3-antenna-4 s3-antenna-1)
    (connected-component s3-antenna-4 s3-antenna-2)
    (connected-component s3-antenna-4 s3-antenna-3)
    (connected-component s3-antenna-4 s3-antenna-5)
    (connected-component s3-antenna-4 s3-antenna-6)

    (connected-component s3-antenna-5 s3-tower-launchpad)
    (connected-component s3-antenna-5 s3-antenna-1)
    (connected-component s3-antenna-5 s3-antenna-2)
    (connected-component s3-antenna-5 s3-antenna-3)
    (connected-component s3-antenna-5 s3-antenna-4)
    (connected-component s3-antenna-5 s3-antenna-6)

    (connected-component s3-antenna-6 s3-tower-launchpad)
    (connected-component s3-antenna-6 s3-antenna-1)
    (connected-component s3-antenna-6 s3-antenna-2)
    (connected-component s3-antenna-6 s3-antenna-3)
    (connected-component s3-antenna-6 s3-antenna-4)
    (connected-component s3-antenna-6 s3-antenna-5)

    (= (max-dock s3-tower-launchpad) 3) 
    (= (max-dock s3-antenna-1) 3)
    (= (max-dock s3-antenna-2) 3) 
    (= (max-dock s3-antenna-3) 3) 
    (= (max-dock s3-antenna-4) 3) 
    (= (max-dock s3-antenna-5) 3) 
    (= (max-dock s3-antenna-6) 3)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    (is-available image front)
    (is-available thermal-image front)
    (is-available image above)
    (is-available thermal-image above)
    (is-available image below)
    (is-available thermal-image below)
    (is-available image left)
    (is-available thermal-image left)
    (is-available image right)
    (is-available thermal-image right)
    (is-available image front-below)
    (is-available thermal-image front-below)

    (is-available signal-measurement front)
    (is-available signal-measurement left)

    (is-available signal-measurement radiation-pattern)
    (is-available signal-measurement dynamic-inspection360)

    
    (is-launch-pad launch-pad)
    (is-dock launch-pad)
    (is-dock dock)

    (is-dynamic-inspection360 dynamic-inspection360)
    (is-radiation-pattern radiation-pattern)

    (different-drone drone1 drone2)
    (different-drone drone1 drone3)
    (different-drone drone1 drone4)
    (different-drone drone2 drone1)
    (different-drone drone2 drone3)
    (different-drone drone2 drone4)
    (different-drone drone3 drone1)
    (different-drone drone3 drone2)
    (different-drone drone3 drone4)
    (different-drone drone4 drone1)
    (different-drone drone4 drone2)
    (different-drone drone4 drone3)

    (different-battery battery1 battery2)
    (different-battery battery1 battery3)
    (different-battery battery1 battery4)
    (different-battery battery1 battery5)
    (different-battery battery1 battery6)
    (different-battery battery1 battery7)
    (different-battery battery1 battery8)
    (different-battery battery2 battery1)
    (different-battery battery2 battery3)
    (different-battery battery2 battery4)
    (different-battery battery2 battery5)
    (different-battery battery2 battery6)
    (different-battery battery2 battery7)
    (different-battery battery2 battery8)
    (different-battery battery3 battery1)
    (different-battery battery3 battery2)
    (different-battery battery3 battery4)
    (different-battery battery3 battery5)
    (different-battery battery3 battery6)
    (different-battery battery3 battery7)
    (different-battery battery3 battery8)
    (different-battery battery4 battery1)
    (different-battery battery4 battery2)
    (different-battery battery4 battery3)
    (different-battery battery4 battery5)
    (different-battery battery4 battery6)
    (different-battery battery4 battery7)
    (different-battery battery4 battery8)
    (different-battery battery5 battery1)
    (different-battery battery5 battery2)
    (different-battery battery5 battery3)
    (different-battery battery5 battery4)
    (different-battery battery5 battery6)
    (different-battery battery5 battery7)
    (different-battery battery5 battery8)
    (different-battery battery6 battery1)
    (different-battery battery6 battery2)
    (different-battery battery6 battery3)
    (different-battery battery6 battery4)
    (different-battery battery6 battery5)
    (different-battery battery6 battery7)
    (different-battery battery6 battery8)
    (different-battery battery7 battery1)
    (different-battery battery7 battery2)
    (different-battery battery7 battery3)
    (different-battery battery7 battery4)
    (different-battery battery7 battery5)
    (different-battery battery7 battery6)
    (different-battery battery7 battery8)
    (different-battery battery8 battery1)
    (different-battery battery8 battery2)
    (different-battery battery8 battery3)
    (different-battery battery8 battery4)
    (different-battery battery8 battery5)
    (different-battery battery8 battery6)
    (different-battery battery8 battery7)


    (has-capability drone1 camera)
    ;(has-capability drone1 signal-measurer)
    (is-at drone1 s1-tower-launchpad launch-pad)
    (has-battery drone1 battery1)
    (= (max-charge-drone drone1) 200)
    (= (velocity drone1) 5)

    (has-capability drone2 camera)
    (has-capability drone2 thermal-camera)
    ;(has-capability drone2 signal-measurer)
    (is-at drone2 s1-tower-launchpad launch-pad)
    (has-battery drone2 battery2)
    (= (max-charge-drone drone2) 200)
    (= (velocity drone2) 1)

    (has-capability drone3 thermal-camera)
    (has-capability drone3 signal-measurer)
    (is-at drone3 s1-tower-launchpad launch-pad)
    (has-battery drone3 battery3)
    (= (max-charge-drone drone3) 200)
    (= (velocity drone3) 2)

    (has-capability drone4 camera)
    ;(has-capability drone4 signal-measurer)
    (is-at drone4 s3-tower-launchpad launch-pad)
    (has-battery drone4 battery4)
    (= (max-charge-drone drone4) 200)
    (= (velocity drone4) 2)
      
    (= (battery-charge battery1) 95)
    (= (battery-charge battery2) 190)
    (= (battery-charge battery3) 200)
    (= (battery-charge battery4) 80)

    (= (battery-charge battery5) 200)
    (= (battery-charge battery6) 200)
    (= (battery-charge battery7) 200)
    (= (battery-charge battery8) 80)


    
    (is-free battery5)
    (is-free battery6)
    (is-free battery7)
    (is-free battery8)

    (is-at-battery battery5 s1-tower-launchpad launch-pad)
    (is-at-battery battery6 s1-tower-launchpad launch-pad)
    (is-at-battery battery7 s1-tower-launchpad launch-pad)  
    (is-at-battery battery8 s3-tower-launchpad launch-pad)   

    (= (max-charge-battery battery1) 200)
    (= (max-charge-battery battery2) 200)
    (= (max-charge-battery battery3) 200)
    (= (max-charge-battery battery4) 80)
    (= (max-charge-battery battery5) 200)
    (= (max-charge-battery battery6) 200)
    (= (max-charge-battery battery7) 200)
    (= (max-charge-battery battery8) 80)
  )

  (:goal (and

    ;scenario goals
    (is-at drone1 s1-tower-launchpad launch-pad)
    (is-at drone2 s2-tower-launchpad launch-pad)
    (is-at drone3 s2-tower-launchpad launch-pad)
    (is-at drone4 s3-tower-launchpad launch-pad)
      
    (know image s1-antenna-1 front-below)  
    (know image s1-antenna-2 front)
    (know image s1-antenna-3 above)
    (know image s1-antenna-4 above)
    (know image s1-antenna-5 front)
    (know image s1-antenna-6 right)
    

    (know image s2-antenna-1 left)
    (know image s2-antenna-2 above)
    (know image s2-antenna-3 front)
    (know image s2-antenna-4 above)
    (know image s2-antenna-5 front)
    (know image s2-antenna-6 right)

    (know thermal-image s2-antenna-2 above)
    (know thermal-image s2-antenna-3 front)

    (know image s3-antenna-1 left)
    (know image s3-antenna-1 above)
    (know image s3-antenna-1 front)

    ;extra goals
    (know signal-measurement s3-antenna-1 front)
    (know signal-measurement s3-antenna-2 left)
    (know signal-measurement s3-antenna-3 left)
    (know signal-measurement s3-antenna-4 left)
    (know signal-measurement s3-antenna-5 left)
    (know signal-measurement s3-antenna-6 left)

    )
  )

  (:metric minimize (total-time))
)






















 
