; added a launchpad perspective for each drone
; added the is-clear-perspective for the relevant perspectives in the initial state



(define (problem asi-dur-problem-fullswap)
  (:domain asi-dur-domain-fullswap)
 
  (:objects 
	
    s7-tower-launchpad s7-antenna-1 s7-antenna-2 s7-antenna-3 s7-antenna-4 s7-antenna-5 s7-antenna-6 - component
    s8-tower-launchpad s8-antenna-1 s8-antenna-2 s8-antenna-3 s8-antenna-4 s8-antenna-5 s8-antenna-6 - component
    s9-tower-launchpad s9-antenna-1 s9-antenna-2 s9-antenna-3 s9-antenna-4 s9-antenna-5 s9-antenna-6 - component

    front above below left right front-below launch-pad dock radiation-pattern dynamic-inspection360 - perspective 
    drone3 drone5 - drone
  
  )

  (:init

    ;distance between components

    (= (distance s7-tower-launchpad s8-tower-launchpad) 40.6126148)
    (= (distance s7-tower-launchpad s9-tower-launchpad) 40.6126148)
    (= (distance s8-tower-launchpad s7-tower-launchpad) 40.6126148)
    (= (distance s8-tower-launchpad s9-tower-launchpad) 29.1339746)
    (= (distance s9-tower-launchpad s7-tower-launchpad) 40.6126148)
    (= (distance s9-tower-launchpad s8-tower-launchpad) 29.1339746)


    ;s7-site

    (is-perspective launch-pad s7-tower-launchpad)
    (is-charging-dock s7-tower-launchpad launch-pad)
    (= (distance s7-tower-launchpad s7-antenna-1) 7)
    (= (distance s7-tower-launchpad s7-antenna-2) 7)
    (= (distance s7-tower-launchpad s7-antenna-3) 8)
    (= (distance s7-tower-launchpad s7-antenna-4) 8)
    (= (distance s7-tower-launchpad s7-antenna-5) 7)
    (= (distance s7-tower-launchpad s7-antenna-6) 7)

    (is-perspective dynamic-inspection360 s7-antenna-1)
    (is-perspective radiation-pattern s7-antenna-1)
    (is-perspective dock s7-antenna-1)
    (is-perspective front s7-antenna-1)
    (is-perspective above s7-antenna-1)
    (is-perspective below s7-antenna-1)
    (is-perspective left s7-antenna-1)
    (is-perspective right s7-antenna-1)
    (is-perspective front-below s7-antenna-1)
    (is-clear-perspective dynamic-inspection360 s7-antenna-1)
    (is-clear-perspective radiation-pattern s7-antenna-1)
    (is-clear-perspective front s7-antenna-1)
    (is-clear-perspective above s7-antenna-1)
    (is-clear-perspective below s7-antenna-1)
    (is-clear-perspective left s7-antenna-1)
    (is-clear-perspective right s7-antenna-1)
    (is-clear-perspective front-below s7-antenna-1)
    (= (distance s7-antenna-1 s7-tower-launchpad) 29)
    (= (distance s7-antenna-1 s7-antenna-2) 1)
    (= (distance s7-antenna-1 s7-antenna-3) 2)
    (= (distance s7-antenna-1 s7-antenna-4) 2)
    (= (distance s7-antenna-1 s7-antenna-5) 2)
    (= (distance s7-antenna-1 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-2)
    (is-perspective radiation-pattern s7-antenna-2)
    (is-perspective dock s7-antenna-2)
    (is-perspective front s7-antenna-2)
    (is-perspective above s7-antenna-2)
    (is-perspective below s7-antenna-2)
    (is-perspective left s7-antenna-2)
    (is-perspective right s7-antenna-2)
    (is-perspective front-below s7-antenna-2)
    (is-clear-perspective dynamic-inspection360 s7-antenna-2)
    (is-clear-perspective radiation-pattern s7-antenna-2)
    (is-clear-perspective front s7-antenna-2)
    (is-clear-perspective above s7-antenna-2)
    (is-clear-perspective below s7-antenna-2)
    (is-clear-perspective left s7-antenna-2)
    (is-clear-perspective right s7-antenna-2)
    (is-clear-perspective front-below s7-antenna-2)
    (= (distance s7-antenna-2 s7-tower-launchpad) 29)
    (= (distance s7-antenna-2 s7-antenna-1) 1)
    (= (distance s7-antenna-2 s7-antenna-3) 2)
    (= (distance s7-antenna-2 s7-antenna-4) 2)
    (= (distance s7-antenna-2 s7-antenna-5) 2)
    (= (distance s7-antenna-2 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-3)
    (is-perspective radiation-pattern s7-antenna-3)
    (is-perspective dock s7-antenna-3)
    (is-perspective front s7-antenna-3)
    (is-perspective above s7-antenna-3)
    (is-perspective below s7-antenna-3)
    (is-perspective left s7-antenna-3)
    (is-perspective right s7-antenna-3)
    (is-perspective front-below s7-antenna-3)
    (is-clear-perspective dynamic-inspection360 s7-antenna-3)
    (is-clear-perspective radiation-pattern s7-antenna-3)
    (is-clear-perspective front s7-antenna-3)
    (is-clear-perspective above s7-antenna-3)
    (is-clear-perspective below s7-antenna-3)
    (is-clear-perspective left s7-antenna-3)
    (is-clear-perspective right s7-antenna-3)
    (is-clear-perspective front-below s7-antenna-3)
    (= (distance s7-antenna-3 s7-tower-launchpad) 30)
    (= (distance s7-antenna-3 s7-antenna-1) 2)
    (= (distance s7-antenna-3 s7-antenna-2) 2)
    (= (distance s7-antenna-3 s7-antenna-4) 1)
    (= (distance s7-antenna-3 s7-antenna-5) 2)
    (= (distance s7-antenna-3 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-4)
    (is-perspective radiation-pattern s7-antenna-4)
    (is-perspective dock s7-antenna-4)
    (is-perspective front s7-antenna-4)
    (is-perspective above s7-antenna-4)
    (is-perspective below s7-antenna-4)
    (is-perspective left s7-antenna-4)
    (is-perspective right s7-antenna-4)
    (is-perspective front-below s7-antenna-4)
    (is-clear-perspective dynamic-inspection360 s7-antenna-4)
    (is-clear-perspective radiation-pattern s7-antenna-4)
    (is-clear-perspective front s7-antenna-4)
    (is-clear-perspective above s7-antenna-4)
    (is-clear-perspective below s7-antenna-4)
    (is-clear-perspective left s7-antenna-4)
    (is-clear-perspective right s7-antenna-4)
    (is-clear-perspective front-below s7-antenna-4)
    (= (distance s7-antenna-4 s7-tower-launchpad) 30)
    (= (distance s7-antenna-4 s7-antenna-1) 2)
    (= (distance s7-antenna-4 s7-antenna-2) 2)
    (= (distance s7-antenna-4 s7-antenna-3) 1)
    (= (distance s7-antenna-4 s7-antenna-5) 2)
    (= (distance s7-antenna-4 s7-antenna-6) 2)

    (is-perspective dynamic-inspection360 s7-antenna-5)
    (is-perspective radiation-pattern s7-antenna-5)
    (is-perspective dock s7-antenna-5)
    (is-perspective front s7-antenna-5)
    (is-perspective above s7-antenna-5)
    (is-perspective below s7-antenna-5)
    (is-perspective left s7-antenna-5)
    (is-perspective right s7-antenna-5)
    (is-perspective front-below s7-antenna-5)
    (is-clear-perspective dynamic-inspection360 s7-antenna-5)
    (is-clear-perspective radiation-pattern s7-antenna-5)
    (is-clear-perspective front s7-antenna-5)
    (is-clear-perspective above s7-antenna-5)
    (is-clear-perspective below s7-antenna-5)
    (is-clear-perspective left s7-antenna-5)
    (is-clear-perspective right s7-antenna-5)
    (is-clear-perspective front-below s7-antenna-5)
    (= (distance s7-antenna-5 s7-tower-launchpad) 29)
    (= (distance s7-antenna-5 s7-antenna-1) 2)
    (= (distance s7-antenna-5 s7-antenna-2) 2)
    (= (distance s7-antenna-5 s7-antenna-3) 2)
    (= (distance s7-antenna-5 s7-antenna-4) 2)
    (= (distance s7-antenna-5 s7-antenna-6) 1)

    (is-perspective dynamic-inspection360 s7-antenna-6)
    (is-perspective radiation-pattern s7-antenna-6)
    (is-perspective dock s7-antenna-6)
    (is-perspective front s7-antenna-6)
    (is-perspective above s7-antenna-6)
    (is-perspective below s7-antenna-6)
    (is-perspective left s7-antenna-6)
    (is-perspective right s7-antenna-6)
    (is-perspective front-below s7-antenna-6)
    (is-clear-perspective dynamic-inspection360 s7-antenna-6)
    (is-clear-perspective radiation-pattern s7-antenna-6)
    (is-clear-perspective front s7-antenna-6)
    (is-clear-perspective above s7-antenna-6)
    (is-clear-perspective below s7-antenna-6)
    (is-clear-perspective left s7-antenna-6)
    (is-clear-perspective right s7-antenna-6)
    (is-clear-perspective front-below s7-antenna-6)
    (= (distance s7-antenna-6 s7-tower-launchpad) 29)
    (= (distance s7-antenna-6 s7-antenna-1) 2)
    (= (distance s7-antenna-6 s7-antenna-2) 2)
    (= (distance s7-antenna-6 s7-antenna-3) 2)
    (= (distance s7-antenna-6 s7-antenna-4) 2)
    (= (distance s7-antenna-6 s7-antenna-5) 1)

    (= (max-dock s7-tower-launchpad) 0) 
    (= (max-dock s7-antenna-1) 3)
    (= (max-dock s7-antenna-2) 3) 
    (= (max-dock s7-antenna-3) 3) 
    (= (max-dock s7-antenna-4) 3) 
    (= (max-dock s7-antenna-5) 3) 
    (= (max-dock s7-antenna-6) 3)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;s8-site

    (is-perspective launch-pad s8-tower-launchpad)
    ;(is-charging-dock s8-tower-launchpad launch-pad)
    (= (distance s8-tower-launchpad s8-antenna-1) 7)
    (= (distance s8-tower-launchpad s8-antenna-2) 7)
    (= (distance s8-tower-launchpad s8-antenna-3) 8)
    (= (distance s8-tower-launchpad s8-antenna-4) 8)
    (= (distance s8-tower-launchpad s8-antenna-5) 7)
    (= (distance s8-tower-launchpad s8-antenna-6) 7)

    (is-perspective dynamic-inspection360 s8-antenna-1)
    (is-perspective radiation-pattern s8-antenna-1)
    (is-perspective dock s8-antenna-1)
    (is-perspective front s8-antenna-1)
    (is-perspective above s8-antenna-1)
    (is-perspective below s8-antenna-1)
    (is-perspective left s8-antenna-1)
    (is-perspective right s8-antenna-1)
    (is-perspective front-below s8-antenna-1)
    (is-clear-perspective dynamic-inspection360 s8-antenna-1)
    (is-clear-perspective radiation-pattern s8-antenna-1)
    (is-clear-perspective front s8-antenna-1)
    (is-clear-perspective above s8-antenna-1)
    (is-clear-perspective below s8-antenna-1)
    (is-clear-perspective left s8-antenna-1)
    (is-clear-perspective right s8-antenna-1)
    (is-clear-perspective front-below s8-antenna-1)
    (= (distance s8-antenna-1 s8-tower-launchpad) 29)
    (= (distance s8-antenna-1 s8-antenna-2) 1)
    (= (distance s8-antenna-1 s8-antenna-3) 2)
    (= (distance s8-antenna-1 s8-antenna-4) 2)
    (= (distance s8-antenna-1 s8-antenna-5) 2)
    (= (distance s8-antenna-1 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-2)
    (is-perspective radiation-pattern s8-antenna-2)
    (is-perspective dock s8-antenna-2)
    (is-perspective front s8-antenna-2)
    (is-perspective above s8-antenna-2)
    (is-perspective below s8-antenna-2)
    (is-perspective left s8-antenna-2)
    (is-perspective right s8-antenna-2)
    (is-perspective front-below s8-antenna-2)
    (is-clear-perspective dynamic-inspection360 s8-antenna-2)
    (is-clear-perspective radiation-pattern s8-antenna-2)
    (is-clear-perspective front s8-antenna-2)
    (is-clear-perspective above s8-antenna-2)
    (is-clear-perspective below s8-antenna-2)
    (is-clear-perspective left s8-antenna-2)
    (is-clear-perspective right s8-antenna-2)
    (is-clear-perspective front-below s8-antenna-2)
    (= (distance s8-antenna-2 s8-tower-launchpad) 29)
    (= (distance s8-antenna-2 s8-antenna-1) 1)
    (= (distance s8-antenna-2 s8-antenna-3) 2)
    (= (distance s8-antenna-2 s8-antenna-4) 2)
    (= (distance s8-antenna-2 s8-antenna-5) 2)
    (= (distance s8-antenna-2 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-3)
    (is-perspective radiation-pattern s8-antenna-3)
    (is-perspective dock s8-antenna-3)
    (is-perspective front s8-antenna-3)
    (is-perspective above s8-antenna-3)
    (is-perspective below s8-antenna-3)
    (is-perspective left s8-antenna-3)
    (is-perspective right s8-antenna-3)
    (is-perspective front-below s8-antenna-3)
    (is-clear-perspective dynamic-inspection360 s8-antenna-3)
    (is-clear-perspective radiation-pattern s8-antenna-3)
    (is-clear-perspective front s8-antenna-3)
    (is-clear-perspective above s8-antenna-3)
    (is-clear-perspective below s8-antenna-3)
    (is-clear-perspective left s8-antenna-3)
    (is-clear-perspective right s8-antenna-3)
    (is-clear-perspective front-below s8-antenna-3)
    (= (distance s8-antenna-3 s8-tower-launchpad) 30)
    (= (distance s8-antenna-3 s8-antenna-1) 2)
    (= (distance s8-antenna-3 s8-antenna-2) 2)
    (= (distance s8-antenna-3 s8-antenna-4) 1)
    (= (distance s8-antenna-3 s8-antenna-5) 2)
    (= (distance s8-antenna-3 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-4)
    (is-perspective radiation-pattern s8-antenna-4)
    (is-perspective dock s8-antenna-4)
    (is-perspective front s8-antenna-4)
    (is-perspective above s8-antenna-4)
    (is-perspective below s8-antenna-4)
    (is-perspective left s8-antenna-4)
    (is-perspective right s8-antenna-4)
    (is-perspective front-below s8-antenna-4)
    (is-clear-perspective dynamic-inspection360 s8-antenna-4)
    (is-clear-perspective radiation-pattern s8-antenna-4)
    (is-clear-perspective front s8-antenna-4)
    (is-clear-perspective above s8-antenna-4)
    (is-clear-perspective below s8-antenna-4)
    (is-clear-perspective left s8-antenna-4)
    (is-clear-perspective right s8-antenna-4)
    (is-clear-perspective front-below s8-antenna-4)
    (= (distance s8-antenna-4 s8-tower-launchpad) 30)
    (= (distance s8-antenna-4 s8-antenna-1) 2)
    (= (distance s8-antenna-4 s8-antenna-2) 2)
    (= (distance s8-antenna-4 s8-antenna-3) 1)
    (= (distance s8-antenna-4 s8-antenna-5) 2)
    (= (distance s8-antenna-4 s8-antenna-6) 2)

    (is-perspective dynamic-inspection360 s8-antenna-5)
    (is-perspective radiation-pattern s8-antenna-5)
    (is-perspective dock s8-antenna-5)
    (is-perspective front s8-antenna-5)
    (is-perspective above s8-antenna-5)
    (is-perspective below s8-antenna-5)
    (is-perspective left s8-antenna-5)
    (is-perspective right s8-antenna-5)
    (is-perspective front-below s8-antenna-5)
    (is-clear-perspective dynamic-inspection360 s8-antenna-5)
    (is-clear-perspective radiation-pattern s8-antenna-5)
    (is-clear-perspective front s8-antenna-5)
    (is-clear-perspective above s8-antenna-5)
    (is-clear-perspective below s8-antenna-5)
    (is-clear-perspective left s8-antenna-5)
    (is-clear-perspective right s8-antenna-5)
    (is-clear-perspective front-below s8-antenna-5)
    (= (distance s8-antenna-5 s8-tower-launchpad) 29)
    (= (distance s8-antenna-5 s8-antenna-1) 2)
    (= (distance s8-antenna-5 s8-antenna-2) 2)
    (= (distance s8-antenna-5 s8-antenna-3) 2)
    (= (distance s8-antenna-5 s8-antenna-4) 2)
    (= (distance s8-antenna-5 s8-antenna-6) 1)

    (is-perspective dynamic-inspection360 s8-antenna-6)
    (is-perspective radiation-pattern s8-antenna-6)
    (is-perspective dock s8-antenna-6)
    (is-perspective front s8-antenna-6)
    (is-perspective above s8-antenna-6)
    (is-perspective below s8-antenna-6)
    (is-perspective left s8-antenna-6)
    (is-perspective right s8-antenna-6)
    (is-perspective front-below s8-antenna-6)
    (is-clear-perspective dynamic-inspection360 s8-antenna-6)
    (is-clear-perspective radiation-pattern s8-antenna-6)
    (is-clear-perspective front s8-antenna-6)
    (is-clear-perspective above s8-antenna-6)
    (is-clear-perspective below s8-antenna-6)
    (is-clear-perspective left s8-antenna-6)
    (is-clear-perspective right s8-antenna-6)
    (is-clear-perspective front-below s8-antenna-6)
    (= (distance s8-antenna-6 s8-tower-launchpad) 29)
    (= (distance s8-antenna-6 s8-antenna-1) 2)
    (= (distance s8-antenna-6 s8-antenna-2) 2)
    (= (distance s8-antenna-6 s8-antenna-3) 2)
    (= (distance s8-antenna-6 s8-antenna-4) 2)
    (= (distance s8-antenna-6 s8-antenna-5) 1)

    (= (max-dock s8-tower-launchpad) 3) 
    (= (max-dock s8-antenna-1) 3)
    (= (max-dock s8-antenna-2) 3) 
    (= (max-dock s8-antenna-3) 3) 
    (= (max-dock s8-antenna-4) 3) 
    (= (max-dock s8-antenna-5) 3) 
    (= (max-dock s8-antenna-6) 3)

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    ;s9-site

    (is-perspective launch-pad s9-tower-launchpad)
    ;(is-charging-dock s9-tower-launchpad launch-pad)
    (= (distance s9-tower-launchpad s9-antenna-1) 7)
    (= (distance s9-tower-launchpad s9-antenna-2) 7)
    (= (distance s9-tower-launchpad s9-antenna-3) 8)
    (= (distance s9-tower-launchpad s9-antenna-4) 8)
    (= (distance s9-tower-launchpad s9-antenna-5) 7)
    (= (distance s9-tower-launchpad s9-antenna-6) 7)

    (is-perspective dynamic-inspection360 s9-antenna-1)
    (is-perspective radiation-pattern s9-antenna-1)
    (is-perspective dock s9-antenna-1)
    (is-perspective front s9-antenna-1)
    (is-perspective above s9-antenna-1)
    (is-perspective below s9-antenna-1)
    (is-perspective left s9-antenna-1)
    (is-perspective right s9-antenna-1)
    (is-perspective front-below s9-antenna-1)
    (is-clear-perspective dynamic-inspection360 s9-antenna-1)
    (is-clear-perspective radiation-pattern s9-antenna-1)
    (is-clear-perspective front s9-antenna-1)
    (is-clear-perspective above s9-antenna-1)
    (is-clear-perspective below s9-antenna-1)
    (is-clear-perspective left s9-antenna-1)
    (is-clear-perspective right s9-antenna-1)
    (is-clear-perspective front-below s9-antenna-1)
    (= (distance s9-antenna-1 s9-tower-launchpad) 29)
    (= (distance s9-antenna-1 s9-antenna-2) 1)
    (= (distance s9-antenna-1 s9-antenna-3) 2)
    (= (distance s9-antenna-1 s9-antenna-4) 2)
    (= (distance s9-antenna-1 s9-antenna-5) 2)
    (= (distance s9-antenna-1 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-2)
    (is-perspective radiation-pattern s9-antenna-2)
    (is-perspective dock s9-antenna-2)
    (is-perspective front s9-antenna-2)
    (is-perspective above s9-antenna-2)
    (is-perspective below s9-antenna-2)
    (is-perspective left s9-antenna-2)
    (is-perspective right s9-antenna-2)
    (is-perspective front-below s9-antenna-2)
    (is-clear-perspective dynamic-inspection360 s9-antenna-2)
    (is-clear-perspective radiation-pattern s9-antenna-2)
    (is-clear-perspective front s9-antenna-2)
    (is-clear-perspective above s9-antenna-2)
    (is-clear-perspective below s9-antenna-2)
    (is-clear-perspective left s9-antenna-2)
    (is-clear-perspective right s9-antenna-2)
    (is-clear-perspective front-below s9-antenna-2)
    (= (distance s9-antenna-2 s9-tower-launchpad) 29)
    (= (distance s9-antenna-2 s9-antenna-1) 1)
    (= (distance s9-antenna-2 s9-antenna-3) 2)
    (= (distance s9-antenna-2 s9-antenna-4) 2)
    (= (distance s9-antenna-2 s9-antenna-5) 2)
    (= (distance s9-antenna-2 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-3)
    (is-perspective radiation-pattern s9-antenna-3)
    (is-perspective dock s9-antenna-3)
    (is-perspective front s9-antenna-3)
    (is-perspective above s9-antenna-3)
    (is-perspective below s9-antenna-3)
    (is-perspective left s9-antenna-3)
    (is-perspective right s9-antenna-3)
    (is-perspective front-below s9-antenna-3)
    (is-clear-perspective dynamic-inspection360 s9-antenna-3)
    (is-clear-perspective radiation-pattern s9-antenna-3)
    (is-clear-perspective front s9-antenna-3)
    (is-clear-perspective above s9-antenna-3)
    (is-clear-perspective below s9-antenna-3)
    (is-clear-perspective left s9-antenna-3)
    (is-clear-perspective right s9-antenna-3)
    (is-clear-perspective front-below s9-antenna-3)
    (= (distance s9-antenna-3 s9-tower-launchpad) 30)
    (= (distance s9-antenna-3 s9-antenna-1) 2)
    (= (distance s9-antenna-3 s9-antenna-2) 2)
    (= (distance s9-antenna-3 s9-antenna-4) 1)
    (= (distance s9-antenna-3 s9-antenna-5) 2)
    (= (distance s9-antenna-3 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-4)
    (is-perspective radiation-pattern s9-antenna-4)
    (is-perspective dock s9-antenna-4)
    (is-perspective front s9-antenna-4)
    (is-perspective above s9-antenna-4)
    (is-perspective below s9-antenna-4)
    (is-perspective left s9-antenna-4)
    (is-perspective right s9-antenna-4)
    (is-perspective front-below s9-antenna-4)
    (is-clear-perspective dynamic-inspection360 s9-antenna-4)
    (is-clear-perspective radiation-pattern s9-antenna-4)
    (is-clear-perspective front s9-antenna-4)
    (is-clear-perspective above s9-antenna-4)
    (is-clear-perspective below s9-antenna-4)
    (is-clear-perspective left s9-antenna-4)
    (is-clear-perspective right s9-antenna-4)
    (is-clear-perspective front-below s9-antenna-4)
    (= (distance s9-antenna-4 s9-tower-launchpad) 30)
    (= (distance s9-antenna-4 s9-antenna-1) 2)
    (= (distance s9-antenna-4 s9-antenna-2) 2)
    (= (distance s9-antenna-4 s9-antenna-3) 1)
    (= (distance s9-antenna-4 s9-antenna-5) 2)
    (= (distance s9-antenna-4 s9-antenna-6) 2)

    (is-perspective dynamic-inspection360 s9-antenna-5)
    (is-perspective radiation-pattern s9-antenna-5)
    (is-perspective dock s9-antenna-5)
    (is-perspective front s9-antenna-5)
    (is-perspective above s9-antenna-5)
    (is-perspective below s9-antenna-5)
    (is-perspective left s9-antenna-5)
    (is-perspective right s9-antenna-5)
    (is-perspective front-below s9-antenna-5)
    (is-clear-perspective dynamic-inspection360 s9-antenna-5)
    (is-clear-perspective radiation-pattern s9-antenna-5)
    (is-clear-perspective front s9-antenna-5)
    (is-clear-perspective above s9-antenna-5)
    (is-clear-perspective below s9-antenna-5)
    (is-clear-perspective left s9-antenna-5)
    (is-clear-perspective right s9-antenna-5)
    (is-clear-perspective front-below s9-antenna-5)
    (= (distance s9-antenna-5 s9-tower-launchpad) 29)
    (= (distance s9-antenna-5 s9-antenna-1) 2)
    (= (distance s9-antenna-5 s9-antenna-2) 2)
    (= (distance s9-antenna-5 s9-antenna-3) 2)
    (= (distance s9-antenna-5 s9-antenna-4) 2)
    (= (distance s9-antenna-5 s9-antenna-6) 1)

    (is-perspective dynamic-inspection360 s9-antenna-6)
    (is-perspective radiation-pattern s9-antenna-6)
    (is-perspective dock s9-antenna-6)
    (is-perspective front s9-antenna-6)
    (is-perspective above s9-antenna-6)
    (is-perspective below s9-antenna-6)
    (is-perspective left s9-antenna-6)
    (is-perspective right s9-antenna-6)
    (is-perspective front-below s9-antenna-6)
    (is-clear-perspective dynamic-inspection360 s9-antenna-6)
    (is-clear-perspective radiation-pattern s9-antenna-6)
    (is-clear-perspective front s9-antenna-6)
    (is-clear-perspective above s9-antenna-6)
    (is-clear-perspective below s9-antenna-6)
    (is-clear-perspective left s9-antenna-6)
    (is-clear-perspective right s9-antenna-6)
    (is-clear-perspective front-below s9-antenna-6)
    (= (distance s9-antenna-6 s9-tower-launchpad) 29)
    (= (distance s9-antenna-6 s9-antenna-1) 2)
    (= (distance s9-antenna-6 s9-antenna-2) 2)
    (= (distance s9-antenna-6 s9-antenna-3) 2)
    (= (distance s9-antenna-6 s9-antenna-4) 2)
    (= (distance s9-antenna-6 s9-antenna-5) 1)

    (= (max-dock s9-tower-launchpad) 3) 
    (= (max-dock s9-antenna-1) 3)
    (= (max-dock s9-antenna-2) 3) 
    (= (max-dock s9-antenna-3) 3) 
    (= (max-dock s9-antenna-4) 3) 
    (= (max-dock s9-antenna-5) 3) 
    (= (max-dock s9-antenna-6) 3)


    ;;;;;;;;;;;;;;;;;;;;;;;

    (is-available image front)
    (is-available thermal-image front)
    (is-available signal-measurement front)
    (is-available image above)
    (is-available thermal-image above)
    (is-available signal-measurement above)
    (is-available image below)
    (is-available thermal-image below)
    (is-available signal-measurement below)
    (is-available image left)
    (is-available thermal-image left)
    (is-available signal-measurement left)
    (is-available image right)
    (is-available thermal-image right)
    (is-available signal-measurement right)
    (is-available image front-below)
    (is-available thermal-image front-below)
    (is-available signal-measurement front-below)

    (is-available signal-measurement radiation-pattern)
    (is-available signal-measurement dynamic-inspection360)
    
    (is-dock launch-pad)
    (is-dock dock)

    (is-dynamic-inspection360 dynamic-inspection360)
    (is-radiation-pattern radiation-pattern) 

    (different-drone drone5 drone3)
    (different-drone drone3 drone5)

    (not_busy drone5)
    (not_busy drone3)

    ;;;;;;;;;;;;;;;drone start location 2

    (has-capability drone5 camera)
    (has-capability drone5 thermal-camera)
    (has-capability drone5 signal-measurer)
    (is-at drone5 s7-tower-launchpad launch-pad)
    (is-at-component drone5 s7-tower-launchpad)
    (= (drone-charge drone5) 190)
    (= (max-charge-drone drone5) 300)
    (= (velocity drone5) 1)

    (has-capability drone3 thermal-camera)
    (has-capability drone3 signal-measurer)
    (is-at drone3 s7-tower-launchpad launch-pad)
    (is-at-component drone3 s7-tower-launchpad)
    (= (drone-charge drone3) 200)
    (= (max-charge-drone drone3) 300)
    (= (velocity drone3) 2)

  )

  (:goal (and

    ;cluster goals
    (is-at drone3 s7-tower-launchpad launch-pad)
    (is-at drone5 s7-tower-launchpad launch-pad)

    (know image s7-antenna-4 below)
    (know signal-measurement s7-antenna-6 front)
    (know-simultaneous signal-measurement s8-antenna-3 radiation-pattern dynamic-inspection360)
    (know thermal-image s8-antenna-3 above)
    (know signal-measurement s8-antenna-4 above)
    (know signal-measurement s9-antenna-1 above)
    (know image s9-antenna-2 front-below)
    
    )
  )

  (:metric minimize (total-time))
)