(define (problem task)
(:domain droneacharya-domain)
(:objects
    s1-tower-launchpad s2-tower-launchpad s3-tower-launchpad s4-tower-launchpad s5-tower-launchpad s6-tower-launchpad s7-tower-launchpad s8-tower-launchpad s9-tower-launchpad s10-tower-launchpad s11-tower-launchpad s12-tower-launchpad s13-tower-launchpad s14-tower-launchpad s15-tower-launchpad s16-tower-launchpad s17-tower-launchpad s18-tower-launchpad s19-tower-launchpad s20-tower-launchpad s21-tower-launchpad - component
    drone1 drone2 drone3 drone4 drone5 drone6 drone7 drone8 drone9 drone10 drone11 drone12 - drone
    station-1-image station-1-inventory-mapping station-1-signal-measurement station-1-thermal-image station-10-image station-10-inventory-mapping station-10-signal-measurement station-10-thermal-image station-11-image station-11-inventory-mapping station-11-signal-measurement station-11-thermal-image station-12-image station-12-inventory-mapping station-12-signal-measurement station-12-thermal-image station-13-image station-13-inventory-mapping station-13-signal-measurement station-13-thermal-image station-14-image station-14-inventory-mapping station-14-signal-measurement station-14-thermal-image station-15-image station-15-inventory-mapping station-15-signal-measurement station-15-thermal-image station-16-image station-16-inventory-mapping station-16-signal-measurement station-16-thermal-image station-17-image station-17-inventory-mapping station-17-signal-measurement station-17-thermal-image station-18-image station-18-inventory-mapping station-18-signal-measurement station-18-thermal-image station-19-image station-19-inventory-mapping station-19-signal-measurement station-19-thermal-image station-2-image station-2-inventory-mapping station-2-signal-measurement station-2-thermal-image station-20-image station-20-inventory-mapping station-20-signal-measurement station-20-thermal-image station-21-image station-21-inventory-mapping station-21-signal-measurement station-21-thermal-image station-3-image station-3-inventory-mapping station-3-signal-measurement station-3-thermal-image station-4-image station-4-inventory-mapping station-4-signal-measurement station-4-thermal-image station-5-image station-5-inventory-mapping station-5-signal-measurement station-5-thermal-image station-6-image station-6-inventory-mapping station-6-signal-measurement station-6-thermal-image station-7-image station-7-inventory-mapping station-7-signal-measurement station-7-thermal-image station-8-image station-8-inventory-mapping station-8-signal-measurement station-8-thermal-image station-9-image station-9-inventory-mapping station-9-signal-measurement station-9-thermal-image - mission
)
(:init
    (has-capability drone1 camera)
    (has-capability drone1 signal-measurer)
    (has-capability drone2 thermal-camera)
    (has-capability drone3 signal-measurer)
    (has-capability drone4 camera)
    (has-capability drone4 signal-measurer)
    (has-capability drone5 thermal-camera)
    (has-capability drone6 signal-measurer)
    (has-capability drone7 camera)
    (has-capability drone7 signal-measurer)
    (has-capability drone8 thermal-camera)
    (has-capability drone9 signal-measurer)
    (has-capability drone10 camera)
    (has-capability drone10 signal-measurer)
    (has-capability drone11 thermal-camera)
    (has-capability drone12 signal-measurer)

    (is-at drone1 s7-tower-launchpad launch-pad)
    (is-at drone2 s7-tower-launchpad launch-pad)
    (is-at drone3 s7-tower-launchpad launch-pad)
    (is-at drone4 s7-tower-launchpad launch-pad)
    (is-at drone5 s4-tower-launchpad launch-pad)
    (is-at drone6 s7-tower-launchpad launch-pad)
    (is-at drone7 s4-tower-launchpad launch-pad)
    (is-at drone8 s4-tower-launchpad launch-pad)
    (is-at drone9 s4-tower-launchpad launch-pad)
    (is-at drone10 s4-tower-launchpad launch-pad)
    (is-at drone11 s4-tower-launchpad launch-pad)
    (is-at drone12 s4-tower-launchpad launch-pad)

    (not_busy_tactical drone1)
    (not_busy_tactical drone2)
    (not_busy_tactical drone3)
    (not_busy_tactical drone4)
    (not_busy_tactical drone5)
    (not_busy_tactical drone6)
    (not_busy_tactical drone7)
    (not_busy_tactical drone8)
    (not_busy_tactical drone9)
    (not_busy_tactical drone10)
    (not_busy_tactical drone11)
    (not_busy_tactical drone12)

    (not_busy_strategic drone1)
    (not_busy_strategic drone2)
    (not_busy_strategic drone3)
    (not_busy_strategic drone4)
    (not_busy_strategic drone5)
    (not_busy_strategic drone6)
    (not_busy_strategic drone7)
    (not_busy_strategic drone8)
    (not_busy_strategic drone9)
    (not_busy_strategic drone10)
    (not_busy_strategic drone11)
    (not_busy_strategic drone12)

    (has-configuration drone1 config1)
    (has-configuration drone2 config2)
    (has-configuration drone3 config3)
    (has-configuration drone4 config1)
    (has-configuration drone5 config2)
    (has-configuration drone6 config3)
    (has-configuration drone7 config1)
    (has-configuration drone8 config2)
    (has-configuration drone9 config3)
    (has-configuration drone10 config1)
    (has-configuration drone11 config2)
    (has-configuration drone12 config3)

    (is-perspective launch-pad s1-tower-launchpad)
    (is-perspective launch-pad s4-tower-launchpad)
    (is-perspective launch-pad s7-tower-launchpad)
    (is-perspective launch-pad s10-tower-launchpad)
    (is-perspective launch-pad s13-tower-launchpad)
    (is-perspective launch-pad s16-tower-launchpad)
    (is-perspective launch-pad s19-tower-launchpad)


    (is-charging-dock s1-tower-launchpad launch-pad)
    (is-charging-dock s4-tower-launchpad launch-pad)
    (is-charging-dock s7-tower-launchpad launch-pad)
    (is-charging-dock s10-tower-launchpad launch-pad)
    (is-charging-dock s13-tower-launchpad launch-pad)
    (is-charging-dock s16-tower-launchpad launch-pad)
    (is-charging-dock s19-tower-launchpad launch-pad)






    (is-at-component drone1 s1-tower-launchpad)
    (is-at-component drone2 s1-tower-launchpad)
    (is-at-component drone3 s1-tower-launchpad)
    (is-at-component drone4 s4-tower-launchpad)
    (is-at-component drone5 s4-tower-launchpad)
    (is-at-component drone6 s4-tower-launchpad)
    (is-at-component drone7 s10-tower-launchpad)
    (is-at-component drone8 s10-tower-launchpad)
    (is-at-component drone9 s10-tower-launchpad)
    (is-at-component drone10 s16-tower-launchpad)
    (is-at-component drone11 s16-tower-launchpad)
    (is-at-component drone12 s16-tower-launchpad)

    (mission_site station-1-image s1-tower-launchpad)
    (mission_site station-1-inventory-mapping s1-tower-launchpad)
    (mission_site station-1-signal-measurement s1-tower-launchpad)
    (mission_site station-1-thermal-image s1-tower-launchpad)
    (mission_site station-10-image s10-tower-launchpad)
    (mission_site station-10-inventory-mapping s10-tower-launchpad)
    (mission_site station-10-signal-measurement s10-tower-launchpad)
    (mission_site station-10-thermal-image s10-tower-launchpad)
    (mission_site station-11-image s10-tower-launchpad)
    (mission_site station-11-inventory-mapping s10-tower-launchpad)
    (mission_site station-11-signal-measurement s10-tower-launchpad)
    (mission_site station-11-thermal-image s10-tower-launchpad)
    (mission_site station-12-image s10-tower-launchpad)
    (mission_site station-12-inventory-mapping s10-tower-launchpad)
    (mission_site station-12-signal-measurement s10-tower-launchpad)
    (mission_site station-12-thermal-image s10-tower-launchpad)
    (mission_site station-13-image s13-tower-launchpad)
    (mission_site station-13-inventory-mapping s13-tower-launchpad)
    (mission_site station-13-signal-measurement s13-tower-launchpad)
    (mission_site station-13-thermal-image s13-tower-launchpad)
    (mission_site station-14-image s13-tower-launchpad)
    (mission_site station-14-inventory-mapping s13-tower-launchpad)
    (mission_site station-14-signal-measurement s13-tower-launchpad)
    (mission_site station-14-thermal-image s13-tower-launchpad)
    (mission_site station-15-image s13-tower-launchpad)
    (mission_site station-15-inventory-mapping s13-tower-launchpad)
    (mission_site station-15-signal-measurement s13-tower-launchpad)
    (mission_site station-15-thermal-image s13-tower-launchpad)
    (mission_site station-16-image s16-tower-launchpad)
    (mission_site station-16-inventory-mapping s16-tower-launchpad)
    (mission_site station-16-signal-measurement s16-tower-launchpad)
    (mission_site station-16-thermal-image s16-tower-launchpad)
    (mission_site station-17-image s16-tower-launchpad)
    (mission_site station-17-inventory-mapping s16-tower-launchpad)
    (mission_site station-17-signal-measurement s16-tower-launchpad)
    (mission_site station-17-thermal-image s16-tower-launchpad)
    (mission_site station-18-image s16-tower-launchpad)
    (mission_site station-18-inventory-mapping s16-tower-launchpad)
    (mission_site station-18-signal-measurement s16-tower-launchpad)
    (mission_site station-18-thermal-image s16-tower-launchpad)
    (mission_site station-19-image s19-tower-launchpad)
    (mission_site station-19-inventory-mapping s19-tower-launchpad)
    (mission_site station-19-signal-measurement s19-tower-launchpad)
    (mission_site station-19-thermal-image s19-tower-launchpad)
    (mission_site station-2-image s1-tower-launchpad)
    (mission_site station-2-inventory-mapping s1-tower-launchpad)
    (mission_site station-2-signal-measurement s1-tower-launchpad)
    (mission_site station-2-thermal-image s1-tower-launchpad)
    (mission_site station-20-image s19-tower-launchpad)
    (mission_site station-20-inventory-mapping s19-tower-launchpad)
    (mission_site station-20-signal-measurement s19-tower-launchpad)
    (mission_site station-20-thermal-image s19-tower-launchpad)
    (mission_site station-21-image s19-tower-launchpad)
    (mission_site station-21-inventory-mapping s19-tower-launchpad)
    (mission_site station-21-signal-measurement s19-tower-launchpad)
    (mission_site station-21-thermal-image s19-tower-launchpad)
    (mission_site station-3-image s1-tower-launchpad)
    (mission_site station-3-inventory-mapping s1-tower-launchpad)
    (mission_site station-3-signal-measurement s1-tower-launchpad)
    (mission_site station-3-thermal-image s1-tower-launchpad)
    (mission_site station-4-image s4-tower-launchpad)
    (mission_site station-4-inventory-mapping s4-tower-launchpad)
    (mission_site station-4-signal-measurement s4-tower-launchpad)
    (mission_site station-4-thermal-image s4-tower-launchpad)
    (mission_site station-5-image s4-tower-launchpad)
    (mission_site station-5-inventory-mapping s4-tower-launchpad)
    (mission_site station-5-signal-measurement s4-tower-launchpad)
    (mission_site station-5-thermal-image s4-tower-launchpad)
    (mission_site station-6-image s4-tower-launchpad)
    (mission_site station-6-inventory-mapping s4-tower-launchpad)
    (mission_site station-6-signal-measurement s4-tower-launchpad)
    (mission_site station-6-thermal-image s4-tower-launchpad)
    (mission_site station-7-image s7-tower-launchpad)
    (mission_site station-7-inventory-mapping s7-tower-launchpad)
    (mission_site station-7-signal-measurement s7-tower-launchpad)
    (mission_site station-7-thermal-image s7-tower-launchpad)
    (mission_site station-8-image s7-tower-launchpad)
    (mission_site station-8-inventory-mapping s7-tower-launchpad)
    (mission_site station-8-signal-measurement s7-tower-launchpad)
    (mission_site station-8-thermal-image s7-tower-launchpad)
    (mission_site station-9-image s7-tower-launchpad)
    (mission_site station-9-inventory-mapping s7-tower-launchpad)
    (mission_site station-9-signal-measurement s7-tower-launchpad)
    (mission_site station-9-thermal-image s7-tower-launchpad)

    (mission_station station-1-image s1-tower-launchpad)
    (mission_station station-1-inventory-mapping s1-tower-launchpad)
    (mission_station station-1-signal-measurement s1-tower-launchpad)
    (mission_station station-1-thermal-image s1-tower-launchpad)
    (mission_station station-10-image s10-tower-launchpad)
    (mission_station station-10-inventory-mapping s10-tower-launchpad)
    (mission_station station-10-signal-measurement s10-tower-launchpad)
    (mission_station station-10-thermal-image s10-tower-launchpad)
    (mission_station station-11-image s11-tower-launchpad)
    (mission_station station-11-inventory-mapping s11-tower-launchpad)
    (mission_station station-11-signal-measurement s11-tower-launchpad)
    (mission_station station-11-thermal-image s11-tower-launchpad)
    (mission_station station-12-image s12-tower-launchpad)
    (mission_station station-12-inventory-mapping s12-tower-launchpad)
    (mission_station station-12-signal-measurement s12-tower-launchpad)
    (mission_station station-12-thermal-image s12-tower-launchpad)
    (mission_station station-13-image s13-tower-launchpad)
    (mission_station station-13-inventory-mapping s13-tower-launchpad)
    (mission_station station-13-signal-measurement s13-tower-launchpad)
    (mission_station station-13-thermal-image s13-tower-launchpad)
    (mission_station station-14-image s14-tower-launchpad)
    (mission_station station-14-inventory-mapping s14-tower-launchpad)
    (mission_station station-14-signal-measurement s14-tower-launchpad)
    (mission_station station-14-thermal-image s14-tower-launchpad)
    (mission_station station-15-image s15-tower-launchpad)
    (mission_station station-15-inventory-mapping s15-tower-launchpad)
    (mission_station station-15-signal-measurement s15-tower-launchpad)
    (mission_station station-15-thermal-image s15-tower-launchpad)
    (mission_station station-16-image s16-tower-launchpad)
    (mission_station station-16-inventory-mapping s16-tower-launchpad)
    (mission_station station-16-signal-measurement s16-tower-launchpad)
    (mission_station station-16-thermal-image s16-tower-launchpad)
    (mission_station station-17-image s17-tower-launchpad)
    (mission_station station-17-inventory-mapping s17-tower-launchpad)
    (mission_station station-17-signal-measurement s17-tower-launchpad)
    (mission_station station-17-thermal-image s17-tower-launchpad)
    (mission_station station-18-image s18-tower-launchpad)
    (mission_station station-18-inventory-mapping s18-tower-launchpad)
    (mission_station station-18-signal-measurement s18-tower-launchpad)
    (mission_station station-18-thermal-image s18-tower-launchpad)
    (mission_station station-19-image s19-tower-launchpad)
    (mission_station station-19-inventory-mapping s19-tower-launchpad)
    (mission_station station-19-signal-measurement s19-tower-launchpad)
    (mission_station station-19-thermal-image s19-tower-launchpad)
    (mission_station station-2-image s2-tower-launchpad)
    (mission_station station-2-inventory-mapping s2-tower-launchpad)
    (mission_station station-2-signal-measurement s2-tower-launchpad)
    (mission_station station-2-thermal-image s2-tower-launchpad)
    (mission_station station-20-image s20-tower-launchpad)
    (mission_station station-20-inventory-mapping s20-tower-launchpad)
    (mission_station station-20-signal-measurement s20-tower-launchpad)
    (mission_station station-20-thermal-image s20-tower-launchpad)
    (mission_station station-21-image s21-tower-launchpad)
    (mission_station station-21-inventory-mapping s21-tower-launchpad)
    (mission_station station-21-signal-measurement s21-tower-launchpad)
    (mission_station station-21-thermal-image s21-tower-launchpad)
    (mission_station station-3-image s3-tower-launchpad)
    (mission_station station-3-inventory-mapping s3-tower-launchpad)
    (mission_station station-3-signal-measurement s3-tower-launchpad)
    (mission_station station-3-thermal-image s3-tower-launchpad)
    (mission_station station-4-image s4-tower-launchpad)
    (mission_station station-4-inventory-mapping s4-tower-launchpad)
    (mission_station station-4-signal-measurement s4-tower-launchpad)
    (mission_station station-4-thermal-image s4-tower-launchpad)
    (mission_station station-5-image s5-tower-launchpad)
    (mission_station station-5-inventory-mapping s5-tower-launchpad)
    (mission_station station-5-signal-measurement s5-tower-launchpad)
    (mission_station station-5-thermal-image s5-tower-launchpad)
    (mission_station station-6-image s6-tower-launchpad)
    (mission_station station-6-inventory-mapping s6-tower-launchpad)
    (mission_station station-6-signal-measurement s6-tower-launchpad)
    (mission_station station-6-thermal-image s6-tower-launchpad)
    (mission_station station-7-image s7-tower-launchpad)
    (mission_station station-7-inventory-mapping s7-tower-launchpad)
    (mission_station station-7-signal-measurement s7-tower-launchpad)
    (mission_station station-7-thermal-image s7-tower-launchpad)
    (mission_station station-8-image s8-tower-launchpad)
    (mission_station station-8-inventory-mapping s8-tower-launchpad)
    (mission_station station-8-signal-measurement s8-tower-launchpad)
    (mission_station station-8-thermal-image s8-tower-launchpad)
    (mission_station station-9-image s9-tower-launchpad)
    (mission_station station-9-inventory-mapping s9-tower-launchpad)
    (mission_station station-9-signal-measurement s9-tower-launchpad)
    (mission_station station-9-thermal-image s9-tower-launchpad)

    (station-available s1-tower-launchpad)
    (station-available s10-tower-launchpad)
    (station-available s11-tower-launchpad)
    (station-available s12-tower-launchpad)
    (station-available s13-tower-launchpad)
    (station-available s14-tower-launchpad)
    (station-available s15-tower-launchpad)
    (station-available s16-tower-launchpad)
    (station-available s17-tower-launchpad)
    (station-available s18-tower-launchpad)
    (station-available s19-tower-launchpad)
    (station-available s2-tower-launchpad)
    (station-available s20-tower-launchpad)
    (station-available s21-tower-launchpad)
    (station-available s3-tower-launchpad)
    (station-available s4-tower-launchpad)
    (station-available s5-tower-launchpad)
    (station-available s6-tower-launchpad)
    (station-available s7-tower-launchpad)
    (station-available s8-tower-launchpad)
    (station-available s9-tower-launchpad)

    (mission_type station-1-image cm-1)
    (mission_type station-1-inventory-mapping im-a-2)
    (mission_type station-1-inventory-mapping im-b-2)
    (mission_type station-1-inventory-mapping im-c-2)
    (mission_type station-1-signal-measurement sm-a-1)
    (mission_type station-1-signal-measurement sm-b-1)
    (mission_type station-1-thermal-image tc-1)
    (mission_type station-10-image cm-1)
    (mission_type station-10-inventory-mapping im-a-2)
    (mission_type station-10-inventory-mapping im-b-2)
    (mission_type station-10-inventory-mapping im-c-2)
    (mission_type station-10-signal-measurement sm-a-1)
    (mission_type station-10-signal-measurement sm-b-1)
    (mission_type station-10-thermal-image tc-1)
    (mission_type station-11-image cm-1)
    (mission_type station-11-inventory-mapping im-a-2)
    (mission_type station-11-inventory-mapping im-b-2)
    (mission_type station-11-inventory-mapping im-c-2)
    (mission_type station-11-signal-measurement sm-a-1)
    (mission_type station-11-signal-measurement sm-b-1)
    (mission_type station-11-thermal-image tc-1)
    (mission_type station-12-image cm-1)
    (mission_type station-12-inventory-mapping im-a-2)
    (mission_type station-12-inventory-mapping im-b-2)
    (mission_type station-12-inventory-mapping im-c-2)
    (mission_type station-12-signal-measurement sm-a-1)
    (mission_type station-12-signal-measurement sm-b-1)
    (mission_type station-12-thermal-image tc-1)
    (mission_type station-13-image cm-1)
    (mission_type station-13-inventory-mapping im-a-2)
    (mission_type station-13-inventory-mapping im-b-2)
    (mission_type station-13-inventory-mapping im-c-2)
    (mission_type station-13-signal-measurement sm-a-1)
    (mission_type station-13-signal-measurement sm-b-1)
    (mission_type station-13-thermal-image tc-1)
    (mission_type station-14-image cm-1)
    (mission_type station-14-inventory-mapping im-a-2)
    (mission_type station-14-inventory-mapping im-b-2)
    (mission_type station-14-inventory-mapping im-c-2)
    (mission_type station-14-signal-measurement sm-a-1)
    (mission_type station-14-signal-measurement sm-b-1)
    (mission_type station-14-thermal-image tc-1)
    (mission_type station-15-image cm-1)
    (mission_type station-15-inventory-mapping im-a-2)
    (mission_type station-15-inventory-mapping im-b-2)
    (mission_type station-15-inventory-mapping im-c-2)
    (mission_type station-15-signal-measurement sm-a-1)
    (mission_type station-15-signal-measurement sm-b-1)
    (mission_type station-15-thermal-image tc-1)
    (mission_type station-16-image cm-1)
    (mission_type station-16-inventory-mapping im-a-2)
    (mission_type station-16-inventory-mapping im-b-2)
    (mission_type station-16-inventory-mapping im-c-2)
    (mission_type station-16-signal-measurement sm-a-1)
    (mission_type station-16-signal-measurement sm-b-1)
    (mission_type station-16-thermal-image tc-1)
    (mission_type station-17-image cm-1)
    (mission_type station-17-inventory-mapping im-a-2)
    (mission_type station-17-inventory-mapping im-b-2)
    (mission_type station-17-inventory-mapping im-c-2)
    (mission_type station-17-signal-measurement sm-a-1)
    (mission_type station-17-signal-measurement sm-b-1)
    (mission_type station-17-thermal-image tc-1)
    (mission_type station-18-image cm-1)
    (mission_type station-18-inventory-mapping im-a-2)
    (mission_type station-18-inventory-mapping im-b-2)
    (mission_type station-18-inventory-mapping im-c-2)
    (mission_type station-18-signal-measurement sm-a-1)
    (mission_type station-18-signal-measurement sm-b-1)
    (mission_type station-18-thermal-image tc-1)
    (mission_type station-19-image cm-1)
    (mission_type station-19-inventory-mapping im-a-2)
    (mission_type station-19-inventory-mapping im-b-2)
    (mission_type station-19-inventory-mapping im-c-2)
    (mission_type station-19-signal-measurement sm-a-1)
    (mission_type station-19-signal-measurement sm-b-1)
    (mission_type station-19-thermal-image tc-1)
    (mission_type station-2-image cm-1)
    (mission_type station-2-inventory-mapping im-a-2)
    (mission_type station-2-inventory-mapping im-b-2)
    (mission_type station-2-inventory-mapping im-c-2)
    (mission_type station-2-signal-measurement sm-a-1)
    (mission_type station-2-signal-measurement sm-b-1)
    (mission_type station-2-thermal-image tc-1)
    (mission_type station-20-image cm-1)
    (mission_type station-20-inventory-mapping im-a-2)
    (mission_type station-20-inventory-mapping im-b-2)
    (mission_type station-20-inventory-mapping im-c-2)
    (mission_type station-20-signal-measurement sm-a-1)
    (mission_type station-20-signal-measurement sm-b-1)
    (mission_type station-20-thermal-image tc-1)
    (mission_type station-21-image cm-1)
    (mission_type station-21-inventory-mapping im-a-2)
    (mission_type station-21-inventory-mapping im-b-2)
    (mission_type station-21-inventory-mapping im-c-2)
    (mission_type station-21-signal-measurement sm-a-1)
    (mission_type station-21-signal-measurement sm-b-1)
    (mission_type station-21-thermal-image tc-1)
    (mission_type station-3-image cm-1)
    (mission_type station-3-inventory-mapping im-a-2)
    (mission_type station-3-inventory-mapping im-b-2)
    (mission_type station-3-inventory-mapping im-c-2)
    (mission_type station-3-signal-measurement sm-a-1)
    (mission_type station-3-signal-measurement sm-b-1)
    (mission_type station-3-thermal-image tc-1)
    (mission_type station-4-image cm-1)
    (mission_type station-4-inventory-mapping im-a-2)
    (mission_type station-4-inventory-mapping im-b-2)
    (mission_type station-4-inventory-mapping im-c-2)
    (mission_type station-4-signal-measurement sm-a-1)
    (mission_type station-4-signal-measurement sm-b-1)
    (mission_type station-4-thermal-image tc-1)
    (mission_type station-5-image cm-1)
    (mission_type station-5-inventory-mapping im-a-2)
    (mission_type station-5-inventory-mapping im-b-2)
    (mission_type station-5-inventory-mapping im-c-2)
    (mission_type station-5-signal-measurement sm-a-1)
    (mission_type station-5-signal-measurement sm-b-1)
    (mission_type station-5-thermal-image tc-1)
    (mission_type station-6-image cm-1)
    (mission_type station-6-inventory-mapping im-a-2)
    (mission_type station-6-inventory-mapping im-b-2)
    (mission_type station-6-inventory-mapping im-c-2)
    (mission_type station-6-signal-measurement sm-a-1)
    (mission_type station-6-signal-measurement sm-b-1)
    (mission_type station-6-thermal-image tc-1)
    (mission_type station-7-image cm-1)
    (mission_type station-7-inventory-mapping im-a-2)
    (mission_type station-7-inventory-mapping im-b-2)
    (mission_type station-7-inventory-mapping im-c-2)
    (mission_type station-7-signal-measurement sm-a-1)
    (mission_type station-7-signal-measurement sm-b-1)
    (mission_type station-7-thermal-image tc-1)
    (mission_type station-8-image cm-1)
    (mission_type station-8-inventory-mapping im-a-2)
    (mission_type station-8-inventory-mapping im-b-2)
    (mission_type station-8-inventory-mapping im-c-2)
    (mission_type station-8-signal-measurement sm-a-1)
    (mission_type station-8-signal-measurement sm-b-1)
    (mission_type station-8-thermal-image tc-1)
    (mission_type station-9-image cm-1)
    (mission_type station-9-inventory-mapping im-a-2)
    (mission_type station-9-inventory-mapping im-b-2)
    (mission_type station-9-inventory-mapping im-c-2)
    (mission_type station-9-signal-measurement sm-a-1)
    (mission_type station-9-signal-measurement sm-b-1)
    (mission_type station-9-thermal-image tc-1)


    (has-configuration drone1 config1)
    (has-configuration drone2 config2)
    (has-configuration drone3 config3)
    (has-configuration drone4 config1)
    (has-configuration drone5 config2)
    (has-configuration drone6 config3)
    (has-configuration drone7 config1)
    (has-configuration drone8 config2)
    (has-configuration drone9 config3)
    (has-configuration drone10 config1)
    (has-configuration drone11 config2)
    (has-configuration drone12 config3)

    (at 2000 (active station-1-image))
    (at 2000 (active station-1-inventory-mapping))
    (at 2000 (active station-1-signal-measurement))
    (at 2000 (active station-1-thermal-image))
    (at 2000 (active station-10-image))
    (at 2000 (active station-10-inventory-mapping))
    (at 2000 (active station-10-signal-measurement))
    (at 2000 (active station-10-thermal-image))
    (at 2000 (active station-11-image))
    (at 2000 (active station-11-inventory-mapping))
    (at 2000 (active station-11-signal-measurement))
    (at 2000 (active station-11-thermal-image))
    (at 2000 (active station-12-image))
    (at 2000 (active station-12-inventory-mapping))
    (at 2000 (active station-12-signal-measurement))
    (at 2000 (active station-12-thermal-image))
    (at 2000 (not (active station-13-image)))
    (at 2000 (not (active station-13-inventory-mapping)))
    (at 2000 (not (active station-13-signal-measurement)))
    (at 2000 (not (active station-13-thermal-image)))
    (at 2000 (not (active station-14-image)))
    (at 2000 (not (active station-14-inventory-mapping)))
    (at 2000 (not (active station-14-signal-measurement)))
    (at 2000 (not (active station-14-thermal-image)))
    (at 2000 (not (active station-15-image)))
    (at 2000 (not (active station-15-inventory-mapping)))
    (at 2000 (not (active station-15-signal-measurement)))
    (at 2000 (not (active station-15-thermal-image)))
    (at 2000 (not (is-perspective launch-pad s13-tower-launchpad)))
    (at 2000 (active station-16-image))
    (at 2000 (active station-16-inventory-mapping))
    (at 2000 (active station-16-signal-measurement))
    (at 2000 (active station-16-thermal-image))
    (at 2000 (active station-17-image))
    (at 2000 (active station-17-inventory-mapping))
    (at 2000 (active station-17-signal-measurement))
    (at 2000 (active station-17-thermal-image))
    (at 2000 (active station-18-image))
    (at 2000 (active station-18-inventory-mapping))
    (at 2000 (active station-18-signal-measurement))
    (at 2000 (active station-18-thermal-image))
    (at 2000 (active station-19-image))
    (at 2000 (active station-19-inventory-mapping))
    (at 2000 (active station-19-signal-measurement))
    (at 2000 (active station-19-thermal-image))
    (at 2000 (active station-2-image))
    (at 2000 (active station-2-inventory-mapping))
    (at 2000 (active station-2-signal-measurement))
    (at 2000 (active station-2-thermal-image))
    (at 2000 (active station-20-image))
    (at 2000 (active station-20-inventory-mapping))
    (at 2000 (active station-20-signal-measurement))
    (at 2000 (active station-20-thermal-image))
    (at 2000 (active station-21-image))
    (at 2000 (active station-21-inventory-mapping))
    (at 2000 (active station-21-signal-measurement))
    (at 2000 (active station-21-thermal-image))
    (at 2000 (active station-3-image))
    (at 2000 (active station-3-inventory-mapping))
    (at 2000 (active station-3-signal-measurement))
    (at 2000 (active station-3-thermal-image))
    (at 2000 (active station-4-image))
    (at 2000 (active station-4-inventory-mapping))
    (at 2000 (active station-4-signal-measurement))
    (at 2000 (active station-4-thermal-image))
    (at 2000 (active station-5-image))
    (at 2000 (active station-5-inventory-mapping))
    (at 2000 (active station-5-signal-measurement))
    (at 2000 (active station-5-thermal-image))
    (at 2000 (active station-6-image))
    (at 2000 (active station-6-inventory-mapping))
    (at 2000 (active station-6-signal-measurement))
    (at 2000 (active station-6-thermal-image))
    (at 2000 (active station-7-image))
    (at 2000 (active station-7-inventory-mapping))
    (at 2000 (active station-7-signal-measurement))
    (at 2000 (active station-7-thermal-image))
    (at 2000 (active station-8-image))
    (at 2000 (active station-8-inventory-mapping))
    (at 2000 (active station-8-signal-measurement))
    (at 2000 (active station-8-thermal-image))
    (at 2000 (active station-9-image))
    (at 2000 (active station-9-inventory-mapping))
    (at 2000 (active station-9-signal-measurement))
    (at 2000 (active station-9-thermal-image))


    (= (max-charge drone1) 350)
    (= (max-charge drone2) 350)
    (= (max-charge drone3) 350)
    (= (max-charge drone4) 350)
    (= (max-charge drone5) 350)
    (= (max-charge drone6) 350)
    (= (max-charge drone7) 350)
    (= (max-charge drone8) 350)
    (= (max-charge drone9) 350)
    (= (max-charge drone10) 350)
    (= (max-charge drone11) 350)
    (= (max-charge drone12) 350)

    (= (current-charge drone1) 0)
    (= (current-charge drone2) 0)
    (= (current-charge drone3) 0)
    (= (current-charge drone4) 0)
    (= (current-charge drone5) 0)
    (= (current-charge drone6) 0)
    (= (current-charge drone7) 0)
    (= (current-charge drone8) 0)
    (= (current-charge drone9) 0)
    (= (current-charge drone10) 0)
    (= (current-charge drone11) 0)
    (= (current-charge drone12) 0)

    (= (velocity drone1) 2)
    (= (velocity drone2) 4)
    (= (velocity drone3) 3)
    (= (velocity drone4) 2)
    (= (velocity drone5) 4)
    (= (velocity drone6) 3)
    (= (velocity drone7) 2)
    (= (velocity drone8) 4)
    (= (velocity drone9) 3)
    (= (velocity drone10) 2)
    (= (velocity drone11) 4)
    (= (velocity drone12) 3)

    (= (distance s1-tower-launchpad s4-tower-launchpad) 228.344)
    (= (distance s1-tower-launchpad s7-tower-launchpad) 169.971)
    (= (distance s1-tower-launchpad s10-tower-launchpad) 224.081)
    (= (distance s1-tower-launchpad s13-tower-launchpad) 247.151)
    (= (distance s1-tower-launchpad s16-tower-launchpad) 267.51)
    (= (distance s1-tower-launchpad s19-tower-launchpad) 224.999)
    (= (distance s4-tower-launchpad s1-tower-launchpad) 228.344)
    (= (distance s4-tower-launchpad s7-tower-launchpad) 226.628)
    (= (distance s4-tower-launchpad s10-tower-launchpad) 414.476)
    (= (distance s4-tower-launchpad s13-tower-launchpad) 469.931)
    (= (distance s4-tower-launchpad s16-tower-launchpad) 369.332)
    (= (distance s4-tower-launchpad s19-tower-launchpad) 184.039)
    (= (distance s7-tower-launchpad s1-tower-launchpad) 169.971)
    (= (distance s7-tower-launchpad s4-tower-launchpad) 226.628)
    (= (distance s7-tower-launchpad s10-tower-launchpad) 217.146)
    (= (distance s7-tower-launchpad s13-tower-launchpad) 379.496)
    (= (distance s7-tower-launchpad s16-tower-launchpad) 433.178)
    (= (distance s7-tower-launchpad s19-tower-launchpad) 335.187)
    (= (distance s10-tower-launchpad s1-tower-launchpad) 224.081)
    (= (distance s10-tower-launchpad s4-tower-launchpad) 414.476)
    (= (distance s10-tower-launchpad s7-tower-launchpad) 217.146)
    (= (distance s10-tower-launchpad s13-tower-launchpad) 253.362)
    (= (distance s10-tower-launchpad s16-tower-launchpad) 448.223)
    (= (distance s10-tower-launchpad s19-tower-launchpad) 449.073)
    (= (distance s13-tower-launchpad s1-tower-launchpad) 247.151)
    (= (distance s13-tower-launchpad s4-tower-launchpad) 469.931)
    (= (distance s13-tower-launchpad s7-tower-launchpad) 379.496)
    (= (distance s13-tower-launchpad s10-tower-launchpad) 253.362)
    (= (distance s13-tower-launchpad s16-tower-launchpad) 282.585)
    (= (distance s13-tower-launchpad s19-tower-launchpad) 397.373)
    (= (distance s16-tower-launchpad s1-tower-launchpad) 267.51)
    (= (distance s16-tower-launchpad s4-tower-launchpad) 369.332)
    (= (distance s16-tower-launchpad s7-tower-launchpad) 433.178)
    (= (distance s16-tower-launchpad s10-tower-launchpad) 448.223)
    (= (distance s16-tower-launchpad s13-tower-launchpad) 282.585)
    (= (distance s16-tower-launchpad s19-tower-launchpad) 204.331)
    (= (distance s19-tower-launchpad s1-tower-launchpad) 224.999)
    (= (distance s19-tower-launchpad s4-tower-launchpad) 184.039)
    (= (distance s19-tower-launchpad s7-tower-launchpad) 335.187)
    (= (distance s19-tower-launchpad s10-tower-launchpad) 449.073)
    (= (distance s19-tower-launchpad s13-tower-launchpad) 397.373)
    (= (distance s19-tower-launchpad s16-tower-launchpad) 204.331)

    (= (max-dock s1-tower-launchpad) 0)
    (= (max-dock s4-tower-launchpad) 0)
    (= (max-dock s7-tower-launchpad) 3)
    (= (max-dock s10-tower-launchpad) 0)
    (= (max-dock s13-tower-launchpad) 3)
    (= (max-dock s16-tower-launchpad) 0)
    (= (max-dock s19-tower-launchpad) 3)



    (= (mission_duration station-1-image cm-1) 266.407)
    (= (mission_duration station-1-inventory-mapping im-a-2) 63.987)
    (= (mission_duration station-1-inventory-mapping im-b-2) 80.36)
    (= (mission_duration station-1-inventory-mapping im-c-2) 70.915)
    (= (mission_duration station-1-signal-measurement sm-a-1) 302.407)
    (= (mission_duration station-1-signal-measurement sm-b-1) 297.631)
    (= (mission_duration station-1-thermal-image tc-1) 295.24)
    (= (mission_duration station-10-image cm-1) 266.407)
    (= (mission_duration station-10-inventory-mapping im-a-2) 63.987)
    (= (mission_duration station-10-inventory-mapping im-b-2) 80.36)
    (= (mission_duration station-10-inventory-mapping im-c-2) 70.915)
    (= (mission_duration station-10-signal-measurement sm-a-1) 302.407)
    (= (mission_duration station-10-signal-measurement sm-b-1) 297.631)
    (= (mission_duration station-10-thermal-image tc-1) 295.24)
    (= (mission_duration station-11-image cm-1) 312.755)
    (= (mission_duration station-11-inventory-mapping im-a-2) 154.163)
    (= (mission_duration station-11-inventory-mapping im-b-2) 144.704)
    (= (mission_duration station-11-inventory-mapping im-c-2) 118.97)
    (= (mission_duration station-11-signal-measurement sm-a-1) 348.755)
    (= (mission_duration station-11-signal-measurement sm-b-1) 328.53)
    (= (mission_duration station-11-thermal-image tc-1) 318.415)
    (= (mission_duration station-12-image cm-1) 314.795)
    (= (mission_duration station-12-inventory-mapping im-a-2) 156.203)
    (= (mission_duration station-12-inventory-mapping im-b-2) 146.744)
    (= (mission_duration station-12-inventory-mapping im-c-2) 120.33)
    (= (mission_duration station-12-signal-measurement sm-a-1) 350.795)
    (= (mission_duration station-12-signal-measurement sm-b-1) 329.89)
    (= (mission_duration station-12-thermal-image tc-1) 319.435)
    (= (mission_duration station-13-image cm-1) 266.407)
    (= (mission_duration station-13-inventory-mapping im-a-2) 63.987)
    (= (mission_duration station-13-inventory-mapping im-b-2) 80.36)
    (= (mission_duration station-13-inventory-mapping im-c-2) 70.915)
    (= (mission_duration station-13-signal-measurement sm-a-1) 302.407)
    (= (mission_duration station-13-signal-measurement sm-b-1) 297.631)
    (= (mission_duration station-13-thermal-image tc-1) 295.24)
    (= (mission_duration station-14-image cm-1) 304.385)
    (= (mission_duration station-14-inventory-mapping im-a-2) 145.792)
    (= (mission_duration station-14-inventory-mapping im-b-2) 136.333)
    (= (mission_duration station-14-inventory-mapping im-c-2) 113.389)
    (= (mission_duration station-14-signal-measurement sm-a-1) 340.385)
    (= (mission_duration station-14-signal-measurement sm-b-1) 322.949)
    (= (mission_duration station-14-thermal-image tc-1) 314.23)
    (= (mission_duration station-15-image cm-1) 304.629)
    (= (mission_duration station-15-inventory-mapping im-a-2) 146.037)
    (= (mission_duration station-15-inventory-mapping im-b-2) 136.578)
    (= (mission_duration station-15-inventory-mapping im-c-2) 113.552)
    (= (mission_duration station-15-signal-measurement sm-a-1) 340.629)
    (= (mission_duration station-15-signal-measurement sm-b-1) 323.112)
    (= (mission_duration station-15-thermal-image tc-1) 314.353)
    (= (mission_duration station-16-image cm-1) 266.407)
    (= (mission_duration station-16-inventory-mapping im-a-2) 63.987)
    (= (mission_duration station-16-inventory-mapping im-b-2) 80.36)
    (= (mission_duration station-16-inventory-mapping im-c-2) 70.915)
    (= (mission_duration station-16-signal-measurement sm-a-1) 302.407)
    (= (mission_duration station-16-signal-measurement sm-b-1) 297.631)
    (= (mission_duration station-16-thermal-image tc-1) 295.24)
    (= (mission_duration station-17-image cm-1) 295.999)
    (= (mission_duration station-17-inventory-mapping im-a-2) 137.407)
    (= (mission_duration station-17-inventory-mapping im-b-2) 127.948)
    (= (mission_duration station-17-inventory-mapping im-c-2) 107.799)
    (= (mission_duration station-17-signal-measurement sm-a-1) 331.999)
    (= (mission_duration station-17-signal-measurement sm-b-1) 317.359)
    (= (mission_duration station-17-thermal-image tc-1) 310.037)
    (= (mission_duration station-18-image cm-1) 294.119)
    (= (mission_duration station-18-inventory-mapping im-a-2) 135.527)
    (= (mission_duration station-18-inventory-mapping im-b-2) 126.068)
    (= (mission_duration station-18-inventory-mapping im-c-2) 106.546)
    (= (mission_duration station-18-signal-measurement sm-a-1) 330.119)
    (= (mission_duration station-18-signal-measurement sm-b-1) 316.106)
    (= (mission_duration station-18-thermal-image tc-1) 309.097)
    (= (mission_duration station-19-image cm-1) 266.407)
    (= (mission_duration station-19-inventory-mapping im-a-2) 63.987)
    (= (mission_duration station-19-inventory-mapping im-b-2) 80.36)
    (= (mission_duration station-19-inventory-mapping im-c-2) 70.915)
    (= (mission_duration station-19-signal-measurement sm-a-1) 302.407)
    (= (mission_duration station-19-signal-measurement sm-b-1) 297.631)
    (= (mission_duration station-19-thermal-image tc-1) 295.24)
    (= (mission_duration station-2-image cm-1) 298.475)
    (= (mission_duration station-2-inventory-mapping im-a-2) 139.883)
    (= (mission_duration station-2-inventory-mapping im-b-2) 130.424)
    (= (mission_duration station-2-inventory-mapping im-c-2) 109.45)
    (= (mission_duration station-2-signal-measurement sm-a-1) 334.475)
    (= (mission_duration station-2-signal-measurement sm-b-1) 319.01)
    (= (mission_duration station-2-thermal-image tc-1) 311.275)
    (= (mission_duration station-20-image cm-1) 306.765)
    (= (mission_duration station-20-inventory-mapping im-a-2) 148.172)
    (= (mission_duration station-20-inventory-mapping im-b-2) 138.713)
    (= (mission_duration station-20-inventory-mapping im-c-2) 114.976)
    (= (mission_duration station-20-signal-measurement sm-a-1) 342.765)
    (= (mission_duration station-20-signal-measurement sm-b-1) 324.536)
    (= (mission_duration station-20-thermal-image tc-1) 315.42)
    (= (mission_duration station-21-image cm-1) 306.765)
    (= (mission_duration station-21-inventory-mapping im-a-2) 148.172)
    (= (mission_duration station-21-inventory-mapping im-b-2) 138.713)
    (= (mission_duration station-21-inventory-mapping im-c-2) 114.976)
    (= (mission_duration station-21-signal-measurement sm-a-1) 342.765)
    (= (mission_duration station-21-signal-measurement sm-b-1) 324.536)
    (= (mission_duration station-21-thermal-image tc-1) 315.42)
    (= (mission_duration station-3-image cm-1) 301.371)
    (= (mission_duration station-3-inventory-mapping im-a-2) 142.779)
    (= (mission_duration station-3-inventory-mapping im-b-2) 133.32)
    (= (mission_duration station-3-inventory-mapping im-c-2) 111.38)
    (= (mission_duration station-3-signal-measurement sm-a-1) 382.834)
    (= (mission_duration station-3-signal-measurement sm-b-1) 320.94)
    (= (mission_duration station-3-thermal-image tc-1) 312.723)
    (= (mission_duration station-4-image cm-1) 266.407)
    (= (mission_duration station-4-inventory-mapping im-a-2) 63.987)
    (= (mission_duration station-4-inventory-mapping im-b-2) 80.36)
    (= (mission_duration station-4-inventory-mapping im-c-2) 70.915)
    (= (mission_duration station-4-signal-measurement sm-a-1) 320.747)
    (= (mission_duration station-4-signal-measurement sm-b-1) 297.631)
    (= (mission_duration station-4-thermal-image tc-1) 295.24)
    (= (mission_duration station-5-image cm-1) 358.024)
    (= (mission_duration station-5-inventory-mapping im-a-2) 153.969)
    (= (mission_duration station-5-inventory-mapping im-b-2) 144.51)
    (= (mission_duration station-5-inventory-mapping im-c-2) 118.84)
    (= (mission_duration station-5-signal-measurement sm-a-1) 394.024)
    (= (mission_duration station-5-signal-measurement sm-b-1) 328.4)
    (= (mission_duration station-5-thermal-image tc-1) 318.319)
    (= (mission_duration station-6-image cm-1) 358.024)
    (= (mission_duration station-6-inventory-mapping im-a-2) 153.969)
    (= (mission_duration station-6-inventory-mapping im-b-2) 144.51)
    (= (mission_duration station-6-inventory-mapping im-c-2) 118.84)
    (= (mission_duration station-6-signal-measurement sm-a-1) 394.024)
    (= (mission_duration station-6-signal-measurement sm-b-1) 328.4)
    (= (mission_duration station-6-thermal-image tc-1) 318.319)
    (= (mission_duration station-7-image cm-1) 266.407)
    (= (mission_duration station-7-inventory-mapping im-a-2) 63.987)
    (= (mission_duration station-7-inventory-mapping im-b-2) 80.36)
    (= (mission_duration station-7-inventory-mapping im-c-2) 70.915)
    (= (mission_duration station-7-signal-measurement sm-a-1) 320.747)
    (= (mission_duration station-7-signal-measurement sm-b-1) 297.631)
    (= (mission_duration station-7-thermal-image tc-1) 295.24)
    (= (mission_duration station-8-image cm-1) 358.024)
    (= (mission_duration station-8-inventory-mapping im-a-2) 153.969)
    (= (mission_duration station-8-inventory-mapping im-b-2) 144.51)
    (= (mission_duration station-8-inventory-mapping im-c-2) 118.84)
    (= (mission_duration station-8-signal-measurement sm-a-1) 394.024)
    (= (mission_duration station-8-signal-measurement sm-b-1) 328.4)
    (= (mission_duration station-8-thermal-image tc-1) 318.319)
    (= (mission_duration station-9-image cm-1) 358.024)
    (= (mission_duration station-9-inventory-mapping im-a-2) 153.969)
    (= (mission_duration station-9-inventory-mapping im-b-2) 144.51)
    (= (mission_duration station-9-inventory-mapping im-c-2) 118.84)
    (= (mission_duration station-9-signal-measurement sm-a-1) 394.024)
    (= (mission_duration station-9-signal-measurement sm-b-1) 328.4)
    (= (mission_duration station-9-thermal-image tc-1) 318.319)

    ;wind


    (active station-13-image)
    (active station-13-inventory-mapping)
    (active station-13-signal-measurement)
    (active station-13-thermal-image)
    (active station-14-image)
    (active station-14-inventory-mapping)
    (active station-14-signal-measurement)
    (active station-14-thermal-image)
    (active station-15-image)
    (active station-15-inventory-mapping)
    (active station-15-signal-measurement)
    (active station-15-thermal-image)


       ; sunlight
        (sunlight-favorable)
       ; (at 600 (not (sunlight-favorable)))
       ; (at 1440 (sunlight-favorable))
       ; (at 2040 (not (sunlight-favorable)))
       ; (at 2880 (sunlight-favorable))
       ; (at 3480 (not (sunlight-favorable)))
       ; (at 4320 (sunlight-favorable))
       ; (at 4920 (not (sunlight-favorable)))
       ; (at 5760 (sunlight-favorable))
       ; (at 4360 (not (sunlight-favorable)))
       ; (at 7200 (sunlight-favorable))
       ; (at 7800 (not (sunlight-favorable)))
       ; (at 8640 (sunlight-favorable))
        (at 9240 (not (sunlight-favorable)))
       ; (at 9840 (sunlight-favorable))
       ; (at 10480 (not (sunlight-favorable)))
       ; (at 10920 (sunlight-favorable))
       ; (at 11520 (not (sunlight-favorable)))
       ; (at 12140 (sunlight-favorable))
       ; (at 13520 (not (sunlight-favorable)))


)
(:goal (and
    (mission_complete station-1-image)
    (mission_complete station-1-inventory-mapping)
    (mission_complete station-1-signal-measurement)
    (mission_complete station-1-thermal-image)
    (mission_complete station-10-image)
    (mission_complete station-10-inventory-mapping)
    (mission_complete station-10-signal-measurement)
    (mission_complete station-10-thermal-image)
    (mission_complete station-11-image)
    (mission_complete station-11-inventory-mapping)
    (mission_complete station-11-signal-measurement)
    (mission_complete station-11-thermal-image)
    (mission_complete station-12-image)
    (mission_complete station-12-inventory-mapping)
    (mission_complete station-12-signal-measurement)
    (mission_complete station-12-thermal-image)
    (mission_complete station-13-image)
    (mission_complete station-13-inventory-mapping)
    (mission_complete station-13-signal-measurement)
    (mission_complete station-13-thermal-image)
    (mission_complete station-14-image)
    (mission_complete station-14-inventory-mapping)
    (mission_complete station-14-signal-measurement)
    (mission_complete station-14-thermal-image)
    (mission_complete station-15-image)
    (mission_complete station-15-inventory-mapping)
    (mission_complete station-15-signal-measurement)
    (mission_complete station-15-thermal-image)
    (mission_complete station-16-image)
    (mission_complete station-16-inventory-mapping)
    (mission_complete station-16-signal-measurement)
    (mission_complete station-16-thermal-image)
    (mission_complete station-17-image)
    (mission_complete station-17-inventory-mapping)
    (mission_complete station-17-signal-measurement)
    (mission_complete station-17-thermal-image)
    (mission_complete station-18-image)
    (mission_complete station-18-inventory-mapping)
    (mission_complete station-18-signal-measurement)
    (mission_complete station-18-thermal-image)
    (mission_complete station-19-image)
    (mission_complete station-19-inventory-mapping)
    (mission_complete station-19-signal-measurement)
    (mission_complete station-19-thermal-image)
    (mission_complete station-2-image)
    (mission_complete station-2-inventory-mapping)
    (mission_complete station-2-signal-measurement)
    (mission_complete station-2-thermal-image)
    (mission_complete station-20-image)
    (mission_complete station-20-inventory-mapping)
    (mission_complete station-20-signal-measurement)
    (mission_complete station-20-thermal-image)
    (mission_complete station-21-image)
    (mission_complete station-21-inventory-mapping)
    (mission_complete station-21-signal-measurement)
    (mission_complete station-21-thermal-image)
    (mission_complete station-3-image)
    (mission_complete station-3-inventory-mapping)
    (mission_complete station-3-signal-measurement)
    (mission_complete station-3-thermal-image)
    (mission_complete station-4-image)
    (mission_complete station-4-inventory-mapping)
    (mission_complete station-4-signal-measurement)
    (mission_complete station-4-thermal-image)
    (mission_complete station-5-image)
    (mission_complete station-5-inventory-mapping)
    (mission_complete station-5-signal-measurement)
    (mission_complete station-5-thermal-image)
    (mission_complete station-6-image)
    (mission_complete station-6-inventory-mapping)
    (mission_complete station-6-signal-measurement)
    (mission_complete station-6-thermal-image)
    (mission_complete station-7-image)
    (mission_complete station-7-inventory-mapping)
    (mission_complete station-7-signal-measurement)
    (mission_complete station-7-thermal-image)
    (mission_complete station-8-image)
    (mission_complete station-8-inventory-mapping)
    (mission_complete station-8-signal-measurement)
    (mission_complete station-8-thermal-image)
    (mission_complete station-9-image)
    (mission_complete station-9-inventory-mapping)
    (mission_complete station-9-signal-measurement)
    (mission_complete station-9-thermal-image)
))
(:metric minimize (total-time))
)
